In [1]:
from google.colab import files
uploaded = files.upload()

Saving TT.zip to TT.zip

In [2]:
import zipfile
import os

zip_path = "/content/TT.zip"

with zipfile.ZipFile(zip_path, "r") as z:
    z.extractall("/content")

print("ZIP extracted successfully")

ZIP extracted successfully

In [3]:
import tarfile
import os

tar_path = "/content/ag-news-project.tar.gz"

with tarfile.open(tar_path, "r:gz") as tar:
    tar.extractall("/content")

print("TAR.GZ extracted successfully")

TAR.GZ extracted successfully

/tmp/ipykernel_2255/1977817572.py:7: DeprecationWarning: Python 3.14 will, by default, filter extracted tar archives and reject files or modify their metadata. Use the filter argument to control this behavior.
  tar.extractall("/content")

In [4]:
!find /content/ag-news-project -maxdepth 2 -type f

/content/ag-news-project/requirements.txt
/content/ag-news-project/README.md
/content/ag-news-project/Untitled1.ipynb
/content/ag-news-project/ag_news_project.py
/content/ag-news-project/.gitignore

In [5]:
%cd /content/ag-news-project

/content/ag-news-project

In [6]:
!pwd

/content/ag-news-project

In [7]:
!pip install -q -r requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 4.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 6.0 MB/s eta 0:00:00
WARNING: The candidate selected for download or install is a yanked version: 'matplotlib' candidate (version 3.9.1 at https://files.pythonhosted.org/packages/0d/cb/78283ec2ded91fb74a2ae9ae93f91a897fa578fa78c8c271a7c147f6b8d6/matplotlib-3.9.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (from https://pypi.org/simple/matplotlib/) (requires-python:>=3.9))
Reason for being yanked: The Windows wheels, under some conditions, caused segfaults in unrelated user code.  Due to this we deleted the Windows wheels to prevent these segfaults, however this caused greater disruption as pip then began to try (and fail) to build 3.9.1 from the sdist on Windows which impacted far more users.  Yanking the whole release is the only tool available to eliminate these failures without changes to on the user side.  The sdist, OSX wheel, and manylinux wheels are all functional and there are no critical bugs in the release.   Downstream packagers should not yank their builds of Matplotlib 3.9.1.  See https://github.com/matplotlib/matplotlib/issues/28551 for details.
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 779.1/779.1 MB 1.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.3/9.3 MB 112.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 547.8/547.8 kB 42.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 251.6/251.6 kB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 99.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.0/18.0 MB 77.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 117.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 314.1/314.1 kB 26.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 4.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 98.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 80.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 54.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 818.5 kB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 7.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 13.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 7.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 176.2/176.2 MB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 316.1/316.1 kB 28.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 566.4/566.4 kB 42.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 113.4 MB/s eta 0:00:00
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.26.0+cu128 requires torch==2.11.0, but you have torch 2.3.1 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
hdbscan 0.8.44 requires scikit-learn>=1.6, but you have scikit-learn 1.5.1 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.1 which is incompatible.
gcsfs 2025.3.0 requires fsspec==2025.3.0, but you have fsspec 2024.5.0 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.

In [8]:
%cd /content/ag-news-project

/content/ag-news-project

In [9]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())

if torch.cuda.is_available():
    print(torch.cuda.get_device_name(0))

2.3.1+cu121
True
Tesla T4

In [10]:
!ls -lah /content

total 272K
drwxr-xr-x 1 root root 4.0K Aug 14 20:51 .
drwxr-xr-x 1 root root 4.0K Aug 14 20:42 ..
drwxr-xr-x 2 root root 4.0K Aug 11 15:27 ag-news-project
-rw-r--r-- 1 root root  40K Aug 14 20:51 ag-news-project.tar.gz
drwxr-xr-x 4 root root 4.0K Aug 10 13:31 .config
drwxr-xr-x 1 root root 4.0K Aug 10 13:31 sample_data
-rw-r--r-- 1 root root  68K Aug 14 20:51 TT.zip
-rw-r--r-- 1 root root 143K Aug 14 20:51 Untitled1.ipynb

In [11]:
!find /content -name "ag_news_project.py" -type f

/content/ag-news-project/ag_news_project.py

In [12]:
!python ag_news_project.py --baseline

Downloading readme: 8.07kB [00:00, 22.7MB/s]
Downloading data: 100% 18.6M/18.6M [00:03<00:00, 5.77MB/s]
Downloading data: 100% 1.23M/1.23M [00:01<00:00, 1.05MB/s]
Generating train split: 100% 120000/120000 [00:00<00:00, 561539.10 examples/s]
Generating test split: 100% 7600/7600 [00:00<00:00, 516213.67 examples/s]
Train size: 51000 | Test size: 7600
label
0    30000
1    15000
2     4500
3     1500
Name: count, dtype: int64
[baseline] accuracy=0.8851 macro_f1=0.8839
Summary written to outputs/summary_report.md

In [13]:
!find outputs -maxdepth 2 -type f

outputs/summary_report.md
outputs/baseline_report.json

In [14]:
!python ag_news_project.py --finetune full

Train size: 51000 | Test size: 7600
label
0    30000
1    15000
2     4500
3     1500
Name: count, dtype: int64
2026-08-14 20:56:51.296372: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tokenizer_config.json: 100% 48.0/48.0 [00:00<00:00, 274kB/s]
config.json: 100% 483/483 [00:00<00:00, 2.77MB/s]
vocab.txt: 232kB [00:00, 1.84MB/s]
tokenizer.json: 466kB [00:00, 8.02MB/s]
Map: 100% 51000/51000 [00:11<00:00, 4378.49 examples/s]
Map: 100% 7600/7600 [00:01<00:00, 5967.59 examples/s]
model.safetensors: 100% 268M/268M [00:07<00:00, 35.8MB/s]
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
{'loss': 0.7415, 'grad_norm': 1.5392261743545532, 'learning_rate': 1.9895441237975744e-05, 'epoch': 0.02}
{'loss': 0.2941, 'grad_norm': 6.35088586807251, 'learning_rate': 1.9790882475951487e-05, 'epoch': 0.03}
{'loss': 0.2889, 'grad_norm': 2.034647226333618, 'learning_rate': 1.968632371392723e-05, 'epoch': 0.05}
{'loss': 0.2525, 'grad_norm': 2.0196518898010254, 'learning_rate': 1.958176495190297e-05, 'epoch': 0.06}
{'loss': 0.2559, 'grad_norm': 0.9041967988014221, 'learning_rate': 1.9477206189878712e-05, 'epoch': 0.08}
{'loss': 0.2352, 'grad_norm': 3.5113325119018555, 'learning_rate': 1.9372647427854455e-05, 'epoch': 0.09}
{'loss': 0.2333, 'grad_norm': 4.385457992553711, 'learning_rate': 1.9268088665830197e-05, 'epoch': 0.11}
{'loss': 0.2029, 'grad_norm': 1.8399527072906494, 'learning_rate': 1.916352990380594e-05, 'epoch': 0.13}
{'loss': 0.1679, 'grad_norm': 2.753187656402588, 'learning_rate': 1.9058971141781683e-05, 'epoch': 0.14}
{'loss': 0.2162, 'grad_norm': 7.141122341156006, 'learning_rate': 1.8954412379757426e-05, 'epoch': 0.16}
{'loss': 0.1817, 'grad_norm': 0.6557410955429077, 'learning_rate': 1.884985361773317e-05, 'epoch': 0.17}
{'loss': 0.1825, 'grad_norm': 0.8388504981994629, 'learning_rate': 1.874529485570891e-05, 'epoch': 0.19}
{'loss': 0.1948, 'grad_norm': 5.044554710388184, 'learning_rate': 1.8640736093684654e-05, 'epoch': 0.2}
{'loss': 0.1654, 'grad_norm': 0.5063199400901794, 'learning_rate': 1.8536177331660393e-05, 'epoch': 0.22}
{'loss': 0.1873, 'grad_norm': 3.7086052894592285, 'learning_rate': 1.8431618569636136e-05, 'epoch': 0.24}
{'loss': 0.1818, 'grad_norm': 6.33733606338501, 'learning_rate': 1.832705980761188e-05, 'epoch': 0.25}
{'loss': 0.1565, 'grad_norm': 2.5651602745056152, 'learning_rate': 1.822250104558762e-05, 'epoch': 0.27}
{'loss': 0.1897, 'grad_norm': 0.5472124218940735, 'learning_rate': 1.8117942283563364e-05, 'epoch': 0.28}
{'loss': 0.1635, 'grad_norm': 4.210836410522461, 'learning_rate': 1.8013383521539107e-05, 'epoch': 0.3}
{'loss': 0.1873, 'grad_norm': 0.7286379933357239, 'learning_rate': 1.790882475951485e-05, 'epoch': 0.31}
{'loss': 0.1277, 'grad_norm': 0.7011186480522156, 'learning_rate': 1.7804265997490592e-05, 'epoch': 0.33}
{'loss': 0.164, 'grad_norm': 4.895730495452881, 'learning_rate': 1.7699707235466335e-05, 'epoch': 0.35}
{'loss': 0.1702, 'grad_norm': 1.0935832262039185, 'learning_rate': 1.7595148473442078e-05, 'epoch': 0.36}
{'loss': 0.1452, 'grad_norm': 0.14178958535194397, 'learning_rate': 1.7490589711417817e-05, 'epoch': 0.38}
{'loss': 0.194, 'grad_norm': 0.20703837275505066, 'learning_rate': 1.738603094939356e-05, 'epoch': 0.39}
{'loss': 0.1709, 'grad_norm': 3.991943597793579, 'learning_rate': 1.7281472187369303e-05, 'epoch': 0.41}
{'loss': 0.1817, 'grad_norm': 1.8110390901565552, 'learning_rate': 1.7176913425345045e-05, 'epoch': 0.42}
{'loss': 0.1786, 'grad_norm': 3.6777851581573486, 'learning_rate': 1.7072354663320788e-05, 'epoch': 0.44}
{'loss': 0.1557, 'grad_norm': 5.454197883605957, 'learning_rate': 1.696779590129653e-05, 'epoch': 0.45}
{'loss': 0.1547, 'grad_norm': 10.219178199768066, 'learning_rate': 1.6863237139272274e-05, 'epoch': 0.47}
{'loss': 0.1698, 'grad_norm': 3.0367963314056396, 'learning_rate': 1.6758678377248013e-05, 'epoch': 0.49}
{'loss': 0.1571, 'grad_norm': 4.107287883758545, 'learning_rate': 1.6654119615223756e-05, 'epoch': 0.5}
{'loss': 0.1129, 'grad_norm': 0.049369461834430695, 'learning_rate': 1.65495608531995e-05, 'epoch': 0.52}
{'loss': 0.1612, 'grad_norm': 0.3509616553783417, 'learning_rate': 1.644500209117524e-05, 'epoch': 0.53}
{'loss': 0.1252, 'grad_norm': 4.941627502441406, 'learning_rate': 1.6340443329150984e-05, 'epoch': 0.55}
{'loss': 0.1346, 'grad_norm': 1.784087061882019, 'learning_rate': 1.6235884567126727e-05, 'epoch': 0.56}
{'loss': 0.1477, 'grad_norm': 8.108357429504395, 'learning_rate': 1.613132580510247e-05, 'epoch': 0.58}
{'loss': 0.1236, 'grad_norm': 0.2613348662853241, 'learning_rate': 1.6026767043078212e-05, 'epoch': 0.6}
{'loss': 0.1523, 'grad_norm': 0.18515492975711823, 'learning_rate': 1.5922208281053955e-05, 'epoch': 0.61}
{'loss': 0.1246, 'grad_norm': 1.9728062152862549, 'learning_rate': 1.5817649519029698e-05, 'epoch': 0.63}
{'loss': 0.0916, 'grad_norm': 4.201798439025879, 'learning_rate': 1.5713090757005437e-05, 'epoch': 0.64}
{'loss': 0.1101, 'grad_norm': 1.0696866512298584, 'learning_rate': 1.560853199498118e-05, 'epoch': 0.66}
{'loss': 0.1271, 'grad_norm': 3.403801679611206, 'learning_rate': 1.5503973232956922e-05, 'epoch': 0.67}
{'loss': 0.1522, 'grad_norm': 0.6666383743286133, 'learning_rate': 1.5399414470932665e-05, 'epoch': 0.69}
{'loss': 0.1269, 'grad_norm': 0.03622642531991005, 'learning_rate': 1.5294855708908408e-05, 'epoch': 0.71}
{'loss': 0.1456, 'grad_norm': 2.5564584732055664, 'learning_rate': 1.519029694688415e-05, 'epoch': 0.72}
{'loss': 0.1452, 'grad_norm': 2.8701066970825195, 'learning_rate': 1.5085738184859893e-05, 'epoch': 0.74}
{'loss': 0.1555, 'grad_norm': 5.378408908843994, 'learning_rate': 1.4981179422835634e-05, 'epoch': 0.75}
{'loss': 0.0837, 'grad_norm': 0.0800178050994873, 'learning_rate': 1.4876620660811375e-05, 'epoch': 0.77}
{'loss': 0.1547, 'grad_norm': 15.013154029846191, 'learning_rate': 1.477206189878712e-05, 'epoch': 0.78}
{'loss': 0.1363, 'grad_norm': 1.8112200498580933, 'learning_rate': 1.4667503136762863e-05, 'epoch': 0.8}
{'loss': 0.1339, 'grad_norm': 0.25201326608657837, 'learning_rate': 1.4562944374738604e-05, 'epoch': 0.82}
{'loss': 0.1051, 'grad_norm': 3.948551893234253, 'learning_rate': 1.4458385612714348e-05, 'epoch': 0.83}
{'loss': 0.1465, 'grad_norm': 3.5403504371643066, 'learning_rate': 1.4353826850690089e-05, 'epoch': 0.85}
{'loss': 0.1459, 'grad_norm': 0.15662388503551483, 'learning_rate': 1.424926808866583e-05, 'epoch': 0.86}
{'loss': 0.1592, 'grad_norm': 6.7720866203308105, 'learning_rate': 1.4144709326641575e-05, 'epoch': 0.88}
{'loss': 0.1173, 'grad_norm': 0.12565717101097107, 'learning_rate': 1.4040150564617316e-05, 'epoch': 0.89}
{'loss': 0.1583, 'grad_norm': 2.981330633163452, 'learning_rate': 1.3935591802593058e-05, 'epoch': 0.91}
{'loss': 0.1447, 'grad_norm': 14.259283065795898, 'learning_rate': 1.38310330405688e-05, 'epoch': 0.93}
{'loss': 0.1073, 'grad_norm': 2.8801355361938477, 'learning_rate': 1.3726474278544544e-05, 'epoch': 0.94}
{'loss': 0.0712, 'grad_norm': 1.9716825485229492, 'learning_rate': 1.3621915516520285e-05, 'epoch': 0.96}
{'loss': 0.1288, 'grad_norm': 0.07673683017492294, 'learning_rate': 1.3517356754496028e-05, 'epoch': 0.97}
{'loss': 0.1613, 'grad_norm': 7.732712745666504, 'learning_rate': 1.341279799247177e-05, 'epoch': 0.99}
 33% 3187/9564 [07:46<14:16,  7.45it/s]
  0% 0/238 [00:00<?, ?it/s]
  1% 2/238 [00:00<00:12, 18.95it/s]
  2% 4/238 [00:00<00:24,  9.64it/s]
  3% 6/238 [00:00<00:24,  9.65it/s]
  3% 8/238 [00:00<00:25,  8.97it/s]
  4% 9/238 [00:00<00:26,  8.54it/s]
  4% 10/238 [00:01<00:27,  8.23it/s]
  5% 12/238 [00:01<00:26,  8.67it/s]
  6% 14/238 [00:01<00:25,  8.83it/s]
  6% 15/238 [00:01<00:25,  8.64it/s]
  7% 16/238 [00:01<00:25,  8.74it/s]
  8% 18/238 [00:02<00:25,  8.72it/s]
  8% 19/238 [00:02<00:24,  8.77it/s]
  8% 20/238 [00:02<00:25,  8.41it/s]
  9% 21/238 [00:02<00:26,  8.13it/s]
 10% 23/238 [00:02<00:23,  9.00it/s]
 10% 24/238 [00:02<00:24,  8.57it/s]
 11% 25/238 [00:02<00:25,  8.27it/s]
 11% 27/238 [00:03<00:23,  8.93it/s]
 12% 28/238 [00:03<00:23,  8.97it/s]
 12% 29/238 [00:03<00:24,  8.67it/s]
 13% 30/238 [00:03<00:23,  8.94it/s]
 13% 31/238 [00:03<00:24,  8.62it/s]
 13% 32/238 [00:03<00:24,  8.50it/s]
 14% 33/238 [00:03<00:23,  8.71it/s]
 14% 34/238 [00:03<00:24,  8.45it/s]
 15% 35/238 [00:03<00:24,  8.32it/s]
 15% 36/238 [00:04<00:24,  8.25it/s]
 16% 38/238 [00:04<00:21,  9.32it/s]
 16% 39/238 [00:04<00:22,  8.78it/s]
 17% 41/238 [00:04<00:20,  9.44it/s]
 18% 43/238 [00:04<00:19,  9.79it/s]
 18% 44/238 [00:04<00:19,  9.76it/s]
 19% 45/238 [00:05<00:20,  9.21it/s]
 20% 47/238 [00:05<00:19,  9.64it/s]
 21% 49/238 [00:05<00:18, 10.31it/s]
 21% 51/238 [00:05<00:19,  9.37it/s]
 22% 53/238 [00:05<00:19,  9.51it/s]
 23% 55/238 [00:06<00:19,  9.35it/s]
 24% 57/238 [00:06<00:18,  9.92it/s]
 25% 59/238 [00:06<00:19,  9.42it/s]
 25% 60/238 [00:06<00:19,  9.36it/s]
 26% 61/238 [00:06<00:19,  8.92it/s]
 26% 62/238 [00:06<00:20,  8.55it/s]
 26% 63/238 [00:07<00:20,  8.35it/s]
 27% 65/238 [00:07<00:19,  9.10it/s]
 28% 66/238 [00:07<00:19,  8.86it/s]
 29% 68/238 [00:07<00:17,  9.46it/s]
 29% 69/238 [00:07<00:19,  8.86it/s]
 30% 71/238 [00:07<00:18,  8.95it/s]
 30% 72/238 [00:07<00:18,  8.76it/s]
 31% 73/238 [00:08<00:19,  8.44it/s]
 31% 74/238 [00:08<00:20,  8.13it/s]
 32% 76/238 [00:08<00:19,  8.47it/s]
 32% 77/238 [00:08<00:19,  8.31it/s]
 33% 79/238 [00:08<00:18,  8.72it/s]
 34% 80/238 [00:08<00:18,  8.42it/s]
 34% 81/238 [00:09<00:19,  8.19it/s]
 35% 83/238 [00:09<00:16,  9.34it/s]
 35% 84/238 [00:09<00:17,  9.01it/s]
 36% 85/238 [00:09<00:17,  8.64it/s]
 37% 87/238 [00:09<00:17,  8.59it/s]
 37% 89/238 [00:09<00:16,  8.81it/s]
 38% 90/238 [00:10<00:17,  8.53it/s]
 39% 92/238 [00:10<00:16,  8.60it/s]
 39% 94/238 [00:10<00:15,  9.52it/s]
 40% 95/238 [00:10<00:15,  9.26it/s]
 41% 97/238 [00:10<00:15,  9.32it/s]
 41% 98/238 [00:10<00:15,  8.85it/s]
 42% 99/238 [00:11<00:16,  8.57it/s]
 42% 101/238 [00:11<00:15,  8.89it/s]
 43% 103/238 [00:11<00:14,  9.22it/s]
 44% 104/238 [00:11<00:14,  9.00it/s]
 44% 105/238 [00:11<00:14,  9.10it/s]
 45% 106/238 [00:11<00:14,  9.09it/s]
 45% 108/238 [00:12<00:13,  9.78it/s]
 46% 109/238 [00:12<00:13,  9.56it/s]
 47% 111/238 [00:12<00:13,  9.36it/s]
 47% 112/238 [00:12<00:14,  8.90it/s]
 47% 113/238 [00:12<00:14,  8.71it/s]
 48% 115/238 [00:12<00:14,  8.60it/s]
 49% 117/238 [00:13<00:13,  9.12it/s]
 50% 118/238 [00:13<00:13,  8.59it/s]
 50% 120/238 [00:13<00:13,  8.82it/s]
 51% 121/238 [00:13<00:13,  8.45it/s]
 52% 123/238 [00:13<00:12,  9.03it/s]
 52% 124/238 [00:13<00:12,  9.17it/s]
 53% 125/238 [00:13<00:12,  8.77it/s]
 53% 126/238 [00:14<00:13,  8.25it/s]
 54% 128/238 [00:14<00:12,  8.84it/s]
 54% 129/238 [00:14<00:12,  8.51it/s]
 55% 130/238 [00:14<00:12,  8.41it/s]
 55% 132/238 [00:14<00:10,  9.76it/s]
 56% 133/238 [00:14<00:10,  9.56it/s]
 56% 134/238 [00:14<00:11,  9.15it/s]
 57% 135/238 [00:15<00:11,  8.91it/s]
 57% 136/238 [00:15<00:12,  8.48it/s]
 58% 137/238 [00:15<00:11,  8.81it/s]
 58% 138/238 [00:15<00:11,  8.80it/s]
 59% 140/238 [00:15<00:10,  9.11it/s]
 59% 141/238 [00:15<00:11,  8.67it/s]
 60% 143/238 [00:15<00:10,  9.04it/s]
 61% 145/238 [00:16<00:10,  9.12it/s]
 61% 146/238 [00:16<00:10,  9.08it/s]
 62% 147/238 [00:16<00:10,  8.79it/s]
 62% 148/238 [00:16<00:10,  8.57it/s]
 63% 150/238 [00:16<00:10,  8.64it/s]
 63% 151/238 [00:16<00:09,  8.78it/s]
 64% 152/238 [00:17<00:09,  8.63it/s]
 65% 154/238 [00:17<00:09,  9.23it/s]
 66% 156/238 [00:17<00:08,  9.66it/s]
 66% 158/238 [00:17<00:07, 10.49it/s]
 67% 160/238 [00:17<00:07, 10.20it/s]
 68% 162/238 [00:18<00:08,  9.16it/s]
 68% 163/238 [00:18<00:08,  8.71it/s]
 69% 164/238 [00:18<00:08,  8.32it/s]
 70% 166/238 [00:18<00:08,  8.56it/s]
 70% 167/238 [00:18<00:08,  8.39it/s]
 71% 168/238 [00:18<00:08,  8.12it/s]
 71% 169/238 [00:18<00:08,  8.01it/s]
 71% 170/238 [00:19<00:08,  8.36it/s]
 72% 171/238 [00:19<00:08,  7.89it/s]
 73% 173/238 [00:19<00:07,  9.27it/s]
 73% 174/238 [00:19<00:07,  8.96it/s]
 74% 176/238 [00:19<00:06,  8.92it/s]
 74% 177/238 [00:19<00:07,  8.61it/s]
 75% 179/238 [00:20<00:06,  9.00it/s]
 76% 180/238 [00:20<00:06,  8.63it/s]
 76% 181/238 [00:20<00:06,  8.31it/s]
 76% 182/238 [00:20<00:06,  8.46it/s]
 77% 184/238 [00:20<00:05,  9.33it/s]
 78% 185/238 [00:20<00:06,  8.76it/s]
 78% 186/238 [00:20<00:06,  8.45it/s]
 79% 187/238 [00:21<00:06,  8.06it/s]
 79% 188/238 [00:21<00:06,  7.87it/s]
 79% 189/238 [00:21<00:06,  7.77it/s]
 80% 190/238 [00:21<00:06,  7.80it/s]
 81% 192/238 [00:21<00:04,  9.27it/s]
 82% 194/238 [00:21<00:04,  9.37it/s]
 82% 196/238 [00:21<00:04, 10.16it/s]
 83% 198/238 [00:22<00:04,  8.98it/s]
 84% 200/238 [00:22<00:04,  9.45it/s]
 84% 201/238 [00:22<00:04,  9.14it/s]
 85% 203/238 [00:22<00:03,  9.72it/s]
 86% 204/238 [00:22<00:03,  9.66it/s]
 87% 206/238 [00:23<00:03,  9.58it/s]
 87% 207/238 [00:23<00:03,  9.07it/s]
 87% 208/238 [00:23<00:03,  8.58it/s]
 88% 209/238 [00:23<00:03,  8.86it/s]
 88% 210/238 [00:23<00:03,  8.35it/s]
 89% 211/238 [00:23<00:03,  8.23it/s]
 89% 212/238 [00:23<00:03,  7.93it/s]
 89% 213/238 [00:23<00:03,  7.78it/s]
 90% 214/238 [00:24<00:03,  7.66it/s]
 90% 215/238 [00:24<00:03,  7.58it/s]
 91% 217/238 [00:24<00:02,  9.08it/s]
 92% 218/238 [00:24<00:02,  8.54it/s]
 92% 219/238 [00:24<00:02,  8.26it/s]
 92% 220/238 [00:24<00:02,  8.16it/s]
 93% 221/238 [00:24<00:02,  7.99it/s]
 94% 223/238 [00:25<00:01,  9.48it/s]
 94% 224/238 [00:25<00:01,  9.46it/s]
 95% 225/238 [00:25<00:01,  9.32it/s]
 95% 226/238 [00:25<00:01,  9.32it/s]
 95% 227/238 [00:25<00:01,  9.24it/s]
 96% 229/238 [00:25<00:00, 10.33it/s]
 97% 231/238 [00:25<00:00,  9.78it/s]
 97% 232/238 [00:26<00:00,  9.30it/s]
 98% 233/238 [00:26<00:00,  9.26it/s]
 99% 235/238 [00:26<00:00,  9.67it/s]
 99% 236/238 [00:26<00:00,  9.17it/s]

{'eval_loss': 0.368071973323822, 'eval_accuracy': 0.8975, 'eval_macro_f1': 0.895961103024935, 'eval_runtime': 26.7394, 'eval_samples_per_second': 284.224, 'eval_steps_per_second': 8.901, 'epoch': 1.0}
 33% 3188/9564 [08:12<14:15,  7.45it/s]
100% 238/238 [00:26<00:00, 10.81it/s]
{'loss': 0.0866, 'grad_norm': 3.532247304916382, 'learning_rate': 1.3308239230447513e-05, 'epoch': 1.0}
{'loss': 0.0846, 'grad_norm': 0.11553506553173065, 'learning_rate': 1.3203680468423254e-05, 'epoch': 1.02}
{'loss': 0.1246, 'grad_norm': 0.06950249522924423, 'learning_rate': 1.3099121706398999e-05, 'epoch': 1.04}
{'loss': 0.0757, 'grad_norm': 0.2538721561431885, 'learning_rate': 1.299456294437474e-05, 'epoch': 1.05}
{'loss': 0.0839, 'grad_norm': 3.118337869644165, 'learning_rate': 1.2890004182350482e-05, 'epoch': 1.07}
{'loss': 0.0841, 'grad_norm': 0.4198249578475952, 'learning_rate': 1.2785445420326223e-05, 'epoch': 1.08}
{'loss': 0.0844, 'grad_norm': 9.05959701538086, 'learning_rate': 1.2680886658301968e-05, 'epoch': 1.1}
{'loss': 0.0903, 'grad_norm': 6.711627960205078, 'learning_rate': 1.2576327896277709e-05, 'epoch': 1.11}
{'loss': 0.0725, 'grad_norm': 3.9388816356658936, 'learning_rate': 1.2471769134253452e-05, 'epoch': 1.13}
{'loss': 0.1235, 'grad_norm': 5.952469348907471, 'learning_rate': 1.2367210372229194e-05, 'epoch': 1.14}
{'loss': 0.0824, 'grad_norm': 13.981562614440918, 'learning_rate': 1.2262651610204937e-05, 'epoch': 1.16}
{'loss': 0.1027, 'grad_norm': 7.954572677612305, 'learning_rate': 1.2158092848180678e-05, 'epoch': 1.18}
{'loss': 0.0822, 'grad_norm': 0.1086815595626831, 'learning_rate': 1.2053534086156419e-05, 'epoch': 1.19}
{'loss': 0.0786, 'grad_norm': 0.538246214389801, 'learning_rate': 1.1948975324132164e-05, 'epoch': 1.21}
{'loss': 0.06, 'grad_norm': 0.06867118924856186, 'learning_rate': 1.1844416562107906e-05, 'epoch': 1.22}
{'loss': 0.1218, 'grad_norm': 7.209405899047852, 'learning_rate': 1.1739857800083647e-05, 'epoch': 1.24}
{'loss': 0.0791, 'grad_norm': 0.07383175194263458, 'learning_rate': 1.1635299038059392e-05, 'epoch': 1.25}
{'loss': 0.1184, 'grad_norm': 23.909740447998047, 'learning_rate': 1.1530740276035133e-05, 'epoch': 1.27}
{'loss': 0.0601, 'grad_norm': 2.292727470397949, 'learning_rate': 1.1426181514010874e-05, 'epoch': 1.29}
{'loss': 0.0856, 'grad_norm': 0.637897253036499, 'learning_rate': 1.1321622751986618e-05, 'epoch': 1.3}
{'loss': 0.0636, 'grad_norm': 1.623855471611023, 'learning_rate': 1.121706398996236e-05, 'epoch': 1.32}
{'loss': 0.0914, 'grad_norm': 3.6191647052764893, 'learning_rate': 1.1112505227938102e-05, 'epoch': 1.33}
{'loss': 0.1063, 'grad_norm': 4.76343297958374, 'learning_rate': 1.1007946465913843e-05, 'epoch': 1.35}
{'loss': 0.0774, 'grad_norm': 3.5726711750030518, 'learning_rate': 1.0903387703889588e-05, 'epoch': 1.36}
{'loss': 0.0756, 'grad_norm': 0.06925647705793381, 'learning_rate': 1.0798828941865329e-05, 'epoch': 1.38}
{'loss': 0.0772, 'grad_norm': 0.05894297733902931, 'learning_rate': 1.0694270179841071e-05, 'epoch': 1.4}
{'loss': 0.111, 'grad_norm': 1.0184829235076904, 'learning_rate': 1.0589711417816814e-05, 'epoch': 1.41}
{'loss': 0.1024, 'grad_norm': 0.12142935395240784, 'learning_rate': 1.0485152655792557e-05, 'epoch': 1.43}
{'loss': 0.0725, 'grad_norm': 0.10082101076841354, 'learning_rate': 1.0380593893768298e-05, 'epoch': 1.44}
{'loss': 0.0947, 'grad_norm': 0.017412900924682617, 'learning_rate': 1.027603513174404e-05, 'epoch': 1.46}
{'loss': 0.0933, 'grad_norm': 3.083932399749756, 'learning_rate': 1.0171476369719783e-05, 'epoch': 1.47}
{'loss': 0.1138, 'grad_norm': 1.873245358467102, 'learning_rate': 1.0066917607695526e-05, 'epoch': 1.49}
{'loss': 0.0859, 'grad_norm': 7.042935371398926, 'learning_rate': 9.962358845671269e-06, 'epoch': 1.51}
{'loss': 0.1113, 'grad_norm': 0.07567670941352844, 'learning_rate': 9.85780008364701e-06, 'epoch': 1.52}
{'loss': 0.0995, 'grad_norm': 0.5677390098571777, 'learning_rate': 9.753241321622753e-06, 'epoch': 1.54}
{'loss': 0.097, 'grad_norm': 1.0041738748550415, 'learning_rate': 9.648682559598495e-06, 'epoch': 1.55}
{'loss': 0.0567, 'grad_norm': 0.1989680677652359, 'learning_rate': 9.544123797574238e-06, 'epoch': 1.57}
{'loss': 0.114, 'grad_norm': 0.15003204345703125, 'learning_rate': 9.43956503554998e-06, 'epoch': 1.58}
{'loss': 0.0844, 'grad_norm': 0.22113002836704254, 'learning_rate': 9.335006273525722e-06, 'epoch': 1.6}
{'loss': 0.0791, 'grad_norm': 3.3762519359588623, 'learning_rate': 9.230447511501465e-06, 'epoch': 1.62}
{'loss': 0.0859, 'grad_norm': 0.0217614583671093, 'learning_rate': 9.125888749477207e-06, 'epoch': 1.63}
{'loss': 0.0654, 'grad_norm': 0.09447477012872696, 'learning_rate': 9.02132998745295e-06, 'epoch': 1.65}
{'loss': 0.1221, 'grad_norm': 0.03818947821855545, 'learning_rate': 8.916771225428693e-06, 'epoch': 1.66}
{'loss': 0.0735, 'grad_norm': 0.2960440218448639, 'learning_rate': 8.812212463404434e-06, 'epoch': 1.68}
{'loss': 0.0997, 'grad_norm': 0.20406006276607513, 'learning_rate': 8.707653701380176e-06, 'epoch': 1.69}
{'loss': 0.0997, 'grad_norm': 4.069189548492432, 'learning_rate': 8.603094939355918e-06, 'epoch': 1.71}
{'loss': 0.0595, 'grad_norm': 0.3982061445713043, 'learning_rate': 8.49853617733166e-06, 'epoch': 1.73}
{'loss': 0.0994, 'grad_norm': 5.716487407684326, 'learning_rate': 8.393977415307403e-06, 'epoch': 1.74}
{'loss': 0.0716, 'grad_norm': 0.7512275576591492, 'learning_rate': 8.289418653283146e-06, 'epoch': 1.76}
{'loss': 0.0922, 'grad_norm': 28.293397903442383, 'learning_rate': 8.184859891258888e-06, 'epoch': 1.77}
{'loss': 0.0431, 'grad_norm': 8.452335357666016, 'learning_rate': 8.08030112923463e-06, 'epoch': 1.79}
{'loss': 0.0559, 'grad_norm': 0.5294677019119263, 'learning_rate': 7.975742367210372e-06, 'epoch': 1.8}

In [15]:
!python ag_news_project.py --finetune lora

Train size: 51000 | Test size: 7600
label
0    30000
1    15000
2     4500
3     1500
Name: count, dtype: int64
2026-08-14 21:23:54.541788: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Map: 100% 51000/51000 [00:09<00:00, 5661.17 examples/s]
Map: 100% 7600/7600 [00:01<00:00, 5880.07 examples/s]
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
trainable params: 741,124 || all params: 67,697,672 || trainable%: 1.0948
{'loss': 1.2274, 'grad_norm': 3.127363681793213, 'learning_rate': 1.9895441237975744e-05, 'epoch': 0.02}
{'loss': 0.9167, 'grad_norm': 1.712904691696167, 'learning_rate': 1.9790882475951487e-05, 'epoch': 0.03}
{'loss': 0.7075, 'grad_norm': 1.3896524906158447, 'learning_rate': 1.968632371392723e-05, 'epoch': 0.05}
{'loss': 0.5655, 'grad_norm': 0.9685628414154053, 'learning_rate': 1.958176495190297e-05, 'epoch': 0.06}
{'loss': 0.4404, 'grad_norm': 1.5603142976760864, 'learning_rate': 1.9477206189878712e-05, 'epoch': 0.08}
{'loss': 0.35, 'grad_norm': 0.9589932560920715, 'learning_rate': 1.9372647427854455e-05, 'epoch': 0.09}
{'loss': 0.3544, 'grad_norm': 2.0780551433563232, 'learning_rate': 1.9268088665830197e-05, 'epoch': 0.11}
{'loss': 0.2852, 'grad_norm': 0.8694896101951599, 'learning_rate': 1.916352990380594e-05, 'epoch': 0.13}
{'loss': 0.2423, 'grad_norm': 1.4078701734542847, 'learning_rate': 1.9058971141781683e-05, 'epoch': 0.14}
{'loss': 0.2674, 'grad_norm': 1.4566274881362915, 'learning_rate': 1.8954412379757426e-05, 'epoch': 0.16}
{'loss': 0.2714, 'grad_norm': 2.293206214904785, 'learning_rate': 1.884985361773317e-05, 'epoch': 0.17}
{'loss': 0.2528, 'grad_norm': 0.7260209918022156, 'learning_rate': 1.874529485570891e-05, 'epoch': 0.19}
{'loss': 0.2386, 'grad_norm': 1.1276627779006958, 'learning_rate': 1.8640736093684654e-05, 'epoch': 0.2}
{'loss': 0.1996, 'grad_norm': 1.2248601913452148, 'learning_rate': 1.8536177331660393e-05, 'epoch': 0.22}
{'loss': 0.2722, 'grad_norm': 2.108870267868042, 'learning_rate': 1.8431618569636136e-05, 'epoch': 0.24}
{'loss': 0.2435, 'grad_norm': 2.1292898654937744, 'learning_rate': 1.832705980761188e-05, 'epoch': 0.25}
{'loss': 0.221, 'grad_norm': 0.7529706954956055, 'learning_rate': 1.822250104558762e-05, 'epoch': 0.27}
{'loss': 0.2302, 'grad_norm': 0.4710056483745575, 'learning_rate': 1.8117942283563364e-05, 'epoch': 0.28}
{'loss': 0.1986, 'grad_norm': 1.4591693878173828, 'learning_rate': 1.8013383521539107e-05, 'epoch': 0.3}
{'loss': 0.2209, 'grad_norm': 2.1124019622802734, 'learning_rate': 1.790882475951485e-05, 'epoch': 0.31}
{'loss': 0.2263, 'grad_norm': 0.3757825195789337, 'learning_rate': 1.7804265997490592e-05, 'epoch': 0.33}
{'loss': 0.2205, 'grad_norm': 2.9815914630889893, 'learning_rate': 1.7699707235466335e-05, 'epoch': 0.35}
{'loss': 0.2198, 'grad_norm': 1.732649803161621, 'learning_rate': 1.7595148473442078e-05, 'epoch': 0.36}
{'loss': 0.2177, 'grad_norm': 0.26820874214172363, 'learning_rate': 1.7490589711417817e-05, 'epoch': 0.38}
{'loss': 0.2155, 'grad_norm': 0.5757892727851868, 'learning_rate': 1.738603094939356e-05, 'epoch': 0.39}
{'loss': 0.2363, 'grad_norm': 2.1635279655456543, 'learning_rate': 1.7281472187369303e-05, 'epoch': 0.41}
{'loss': 0.2554, 'grad_norm': 0.9302257895469666, 'learning_rate': 1.7176913425345045e-05, 'epoch': 0.42}
{'loss': 0.2334, 'grad_norm': 1.295861840248108, 'learning_rate': 1.7072354663320788e-05, 'epoch': 0.44}
{'loss': 0.2144, 'grad_norm': 2.882822036743164, 'learning_rate': 1.696779590129653e-05, 'epoch': 0.45}
{'loss': 0.2509, 'grad_norm': 1.5173536539077759, 'learning_rate': 1.6863237139272274e-05, 'epoch': 0.47}
{'loss': 0.2209, 'grad_norm': 1.455152153968811, 'learning_rate': 1.6758678377248013e-05, 'epoch': 0.49}
{'loss': 0.2371, 'grad_norm': 4.171834468841553, 'learning_rate': 1.6654119615223756e-05, 'epoch': 0.5}
{'loss': 0.1837, 'grad_norm': 0.3815155327320099, 'learning_rate': 1.65495608531995e-05, 'epoch': 0.52}
{'loss': 0.2207, 'grad_norm': 0.6852311491966248, 'learning_rate': 1.644500209117524e-05, 'epoch': 0.53}
{'loss': 0.2079, 'grad_norm': 2.865523099899292, 'learning_rate': 1.6340443329150984e-05, 'epoch': 0.55}
{'loss': 0.2037, 'grad_norm': 0.5192010998725891, 'learning_rate': 1.6235884567126727e-05, 'epoch': 0.56}
{'loss': 0.2074, 'grad_norm': 4.944208145141602, 'learning_rate': 1.613132580510247e-05, 'epoch': 0.58}
{'loss': 0.1904, 'grad_norm': 1.6635379791259766, 'learning_rate': 1.6026767043078212e-05, 'epoch': 0.6}
{'loss': 0.2228, 'grad_norm': 0.7583203315734863, 'learning_rate': 1.5922208281053955e-05, 'epoch': 0.61}
{'loss': 0.1812, 'grad_norm': 3.5240132808685303, 'learning_rate': 1.5817649519029698e-05, 'epoch': 0.63}
{'loss': 0.1722, 'grad_norm': 2.4156668186187744, 'learning_rate': 1.5713090757005437e-05, 'epoch': 0.64}
{'loss': 0.1911, 'grad_norm': 1.4461228847503662, 'learning_rate': 1.560853199498118e-05, 'epoch': 0.66}
{'loss': 0.1856, 'grad_norm': 0.6946219801902771, 'learning_rate': 1.5503973232956922e-05, 'epoch': 0.67}
{'loss': 0.2112, 'grad_norm': 1.5408438444137573, 'learning_rate': 1.5399414470932665e-05, 'epoch': 0.69}
{'loss': 0.2094, 'grad_norm': 0.2904784083366394, 'learning_rate': 1.5294855708908408e-05, 'epoch': 0.71}
{'loss': 0.2125, 'grad_norm': 1.0823875665664673, 'learning_rate': 1.519029694688415e-05, 'epoch': 0.72}
{'loss': 0.2118, 'grad_norm': 2.546262502670288, 'learning_rate': 1.5085738184859893e-05, 'epoch': 0.74}
{'loss': 0.2387, 'grad_norm': 2.3544905185699463, 'learning_rate': 1.4981179422835634e-05, 'epoch': 0.75}
{'loss': 0.1562, 'grad_norm': 0.8383033871650696, 'learning_rate': 1.4876620660811375e-05, 'epoch': 0.77}
{'loss': 0.2347, 'grad_norm': 1.9430322647094727, 'learning_rate': 1.477206189878712e-05, 'epoch': 0.78}
{'loss': 0.2014, 'grad_norm': 1.776716947555542, 'learning_rate': 1.4667503136762863e-05, 'epoch': 0.8}
{'loss': 0.2116, 'grad_norm': 0.5493378043174744, 'learning_rate': 1.4562944374738604e-05, 'epoch': 0.82}
{'loss': 0.1976, 'grad_norm': 2.843456983566284, 'learning_rate': 1.4458385612714348e-05, 'epoch': 0.83}
{'loss': 0.1849, 'grad_norm': 2.075230360031128, 'learning_rate': 1.4353826850690089e-05, 'epoch': 0.85}
{'loss': 0.2084, 'grad_norm': 1.1789568662643433, 'learning_rate': 1.424926808866583e-05, 'epoch': 0.86}
{'loss': 0.211, 'grad_norm': 2.7415904998779297, 'learning_rate': 1.4144709326641575e-05, 'epoch': 0.88}
{'loss': 0.2155, 'grad_norm': 1.394726037979126, 'learning_rate': 1.4040150564617316e-05, 'epoch': 0.89}
{'loss': 0.2228, 'grad_norm': 0.8480067849159241, 'learning_rate': 1.3935591802593058e-05, 'epoch': 0.91}
{'loss': 0.197, 'grad_norm': 3.1849358081817627, 'learning_rate': 1.38310330405688e-05, 'epoch': 0.93}
{'loss': 0.1886, 'grad_norm': 1.7241759300231934, 'learning_rate': 1.3726474278544544e-05, 'epoch': 0.94}
{'loss': 0.1621, 'grad_norm': 1.281950831413269, 'learning_rate': 1.3621915516520285e-05, 'epoch': 0.96}
{'loss': 0.2052, 'grad_norm': 0.7047526836395264, 'learning_rate': 1.3517356754496028e-05, 'epoch': 0.97}
{'loss': 0.2234, 'grad_norm': 2.5697286128997803, 'learning_rate': 1.341279799247177e-05, 'epoch': 0.99}
 33% 3188/9564 [05:10<08:41, 12.22it/s]
  0% 0/238 [00:00<?, ?it/s]
  1% 2/238 [00:00<00:13, 17.75it/s]
  2% 4/238 [00:00<00:25,  9.16it/s]
  3% 6/238 [00:00<00:25,  9.15it/s]
  3% 8/238 [00:00<00:26,  8.54it/s]
  4% 9/238 [00:01<00:28,  8.17it/s]
  4% 10/238 [00:01<00:28,  7.90it/s]
  5% 11/238 [00:01<00:27,  8.25it/s]
  5% 12/238 [00:01<00:27,  8.27it/s]
  6% 14/238 [00:01<00:26,  8.50it/s]
  6% 15/238 [00:01<00:26,  8.30it/s]
  7% 16/238 [00:01<00:26,  8.50it/s]
  7% 17/238 [00:01<00:25,  8.83it/s]
  8% 18/238 [00:02<00:26,  8.28it/s]
  8% 19/238 [00:02<00:26,  8.40it/s]
  8% 20/238 [00:02<00:27,  7.97it/s]
  9% 21/238 [00:02<00:27,  7.77it/s]
 10% 23/238 [00:02<00:24,  8.70it/s]
 10% 24/238 [00:02<00:25,  8.27it/s]
 11% 25/238 [00:02<00:26,  7.98it/s]
 11% 26/238 [00:03<00:25,  8.38it/s]
 11% 27/238 [00:03<00:24,  8.65it/s]
 12% 28/238 [00:03<00:24,  8.71it/s]
 12% 29/238 [00:03<00:25,  8.36it/s]
 13% 30/238 [00:03<00:24,  8.64it/s]
 13% 31/238 [00:03<00:24,  8.41it/s]
 13% 32/238 [00:03<00:24,  8.25it/s]
 14% 33/238 [00:03<00:24,  8.41it/s]
 14% 34/238 [00:04<00:25,  8.11it/s]
 15% 35/238 [00:04<00:25,  8.07it/s]
 15% 36/238 [00:04<00:25,  8.06it/s]
 16% 37/238 [00:04<00:23,  8.52it/s]
 16% 39/238 [00:04<00:23,  8.61it/s]
 17% 41/238 [00:04<00:21,  9.20it/s]
 18% 43/238 [00:05<00:20,  9.41it/s]
 18% 44/238 [00:05<00:20,  9.43it/s]
 19% 45/238 [00:05<00:21,  8.90it/s]
 20% 47/238 [00:05<00:20,  9.24it/s]
 21% 49/238 [00:05<00:19,  9.94it/s]
 21% 50/238 [00:05<00:19,  9.75it/s]
 21% 51/238 [00:05<00:21,  8.80it/s]
 22% 53/238 [00:06<00:20,  9.05it/s]
 23% 55/238 [00:06<00:20,  8.93it/s]
 24% 57/238 [00:06<00:19,  9.46it/s]
 24% 58/238 [00:06<00:20,  8.90it/s]
 25% 59/238 [00:06<00:19,  9.01it/s]
 25% 60/238 [00:06<00:19,  9.01it/s]
 26% 61/238 [00:07<00:21,  8.37it/s]
 26% 62/238 [00:07<00:21,  8.07it/s]
 26% 63/238 [00:07<00:22,  7.81it/s]
 27% 65/238 [00:07<00:20,  8.64it/s]
 28% 66/238 [00:07<00:20,  8.33it/s]
 29% 68/238 [00:07<00:19,  8.94it/s]
 29% 69/238 [00:07<00:19,  8.46it/s]
 29% 70/238 [00:08<00:19,  8.78it/s]
 30% 71/238 [00:08<00:19,  8.47it/s]
 30% 72/238 [00:08<00:20,  8.28it/s]
 31% 73/238 [00:08<00:20,  7.94it/s]
 31% 74/238 [00:08<00:21,  7.62it/s]
 32% 76/238 [00:08<00:20,  8.10it/s]
 32% 77/238 [00:08<00:19,  8.06it/s]
 33% 79/238 [00:09<00:18,  8.54it/s]
 34% 80/238 [00:09<00:19,  8.30it/s]
 34% 81/238 [00:09<00:19,  8.02it/s]
 35% 83/238 [00:09<00:16,  9.17it/s]
 35% 84/238 [00:09<00:17,  8.75it/s]
 36% 85/238 [00:09<00:18,  8.36it/s]
 37% 87/238 [00:10<00:18,  8.35it/s]
 37% 89/238 [00:10<00:17,  8.49it/s]
 38% 90/238 [00:10<00:18,  8.18it/s]
 39% 92/238 [00:10<00:17,  8.36it/s]
 39% 94/238 [00:10<00:15,  9.22it/s]
 40% 95/238 [00:11<00:15,  8.97it/s]
 41% 97/238 [00:11<00:15,  8.91it/s]
 41% 98/238 [00:11<00:16,  8.47it/s]
 42% 99/238 [00:11<00:17,  8.14it/s]
 42% 101/238 [00:11<00:16,  8.52it/s]
 43% 103/238 [00:11<00:15,  8.86it/s]
 44% 104/238 [00:12<00:15,  8.58it/s]
 44% 105/238 [00:12<00:15,  8.65it/s]
 45% 106/238 [00:12<00:15,  8.54it/s]
 45% 107/238 [00:12<00:14,  8.77it/s]
 46% 109/238 [00:12<00:13,  9.26it/s]
 46% 110/238 [00:12<00:13,  9.35it/s]
 47% 111/238 [00:12<00:14,  8.90it/s]
 47% 112/238 [00:12<00:14,  8.40it/s]
 47% 113/238 [00:13<00:15,  8.31it/s]
 48% 115/238 [00:13<00:14,  8.29it/s]
 49% 117/238 [00:13<00:13,  8.95it/s]
 50% 118/238 [00:13<00:14,  8.32it/s]
 50% 120/238 [00:13<00:13,  8.57it/s]
 51% 121/238 [00:14<00:14,  8.21it/s]
 52% 123/238 [00:14<00:12,  8.85it/s]
 52% 124/238 [00:14<00:12,  9.02it/s]
 53% 125/238 [00:14<00:13,  8.66it/s]
 53% 126/238 [00:14<00:13,  8.09it/s]
 54% 128/238 [00:14<00:12,  8.58it/s]
 54% 129/238 [00:14<00:13,  8.25it/s]
 55% 130/238 [00:15<00:13,  8.22it/s]
 55% 132/238 [00:15<00:11,  9.60it/s]
 56% 133/238 [00:15<00:11,  9.43it/s]
 56% 134/238 [00:15<00:11,  8.90it/s]
 57% 135/238 [00:15<00:11,  8.59it/s]
 57% 136/238 [00:15<00:12,  8.14it/s]
 58% 137/238 [00:15<00:11,  8.44it/s]
 58% 138/238 [00:16<00:11,  8.47it/s]
 58% 139/238 [00:16<00:11,  8.80it/s]
 59% 140/238 [00:16<00:11,  8.72it/s]
 59% 141/238 [00:16<00:11,  8.19it/s]
 60% 143/238 [00:16<00:10,  8.80it/s]
 61% 144/238 [00:16<00:10,  9.01it/s]
 61% 145/238 [00:16<00:10,  8.84it/s]
 61% 146/238 [00:16<00:10,  8.69it/s]
 62% 147/238 [00:17<00:10,  8.34it/s]
 62% 148/238 [00:17<00:10,  8.20it/s]
 63% 150/238 [00:17<00:10,  8.31it/s]
 63% 151/238 [00:17<00:10,  8.49it/s]
 64% 152/238 [00:17<00:10,  8.23it/s]
 64% 153/238 [00:17<00:09,  8.56it/s]
 65% 154/238 [00:17<00:09,  8.91it/s]
 66% 156/238 [00:18<00:08,  9.51it/s]
 66% 158/238 [00:18<00:07, 10.19it/s]
 67% 160/238 [00:18<00:07,  9.86it/s]
 68% 161/238 [00:18<00:08,  9.20it/s]
 68% 162/238 [00:18<00:08,  8.70it/s]
 33% 3188/9564 [05:29<08:41, 12.22it/s]
 69% 164/238 [00:19<00:09,  7.82it/s]
 70% 166/238 [00:19<00:08,  8.09it/s]
 70% 167/238 [00:19<00:08,  7.89it/s]
 71% 168/238 [00:19<00:09,  7.75it/s]
 71% 169/238 [00:19<00:09,  7.64it/s]
 71% 170/238 [00:19<00:08,  8.03it/s]
 72% 171/238 [00:19<00:08,  7.59it/s]
 73% 173/238 [00:20<00:07,  8.91it/s]
 73% 174/238 [00:20<00:07,  8.60it/s]
 74% 176/238 [00:20<00:07,  8.59it/s]
 74% 177/238 [00:20<00:07,  8.41it/s]
 75% 179/238 [00:20<00:06,  8.83it/s]
 76% 180/238 [00:20<00:06,  8.42it/s]
 76% 181/238 [00:21<00:07,  8.06it/s]
 76% 182/238 [00:21<00:06,  8.21it/s]
 77% 184/238 [00:21<00:05,  9.06it/s]
 78% 185/238 [00:21<00:06,  8.46it/s]
 78% 186/238 [00:21<00:06,  8.08it/s]
 79% 187/238 [00:21<00:06,  7.82it/s]
 79% 188/238 [00:21<00:06,  7.62it/s]
 79% 189/238 [00:22<00:06,  7.50it/s]
 80% 190/238 [00:22<00:06,  7.51it/s]
 81% 192/238 [00:22<00:05,  8.96it/s]
 81% 193/238 [00:22<00:04,  9.12it/s]
 82% 194/238 [00:22<00:04,  8.91it/s]
 82% 196/238 [00:22<00:04,  9.90it/s]
 83% 197/238 [00:22<00:04,  9.07it/s]
 83% 198/238 [00:23<00:04,  8.53it/s]
 84% 200/238 [00:23<00:04,  9.18it/s]
 84% 201/238 [00:23<00:04,  8.77it/s]
 85% 202/238 [00:23<00:03,  9.00it/s]
 86% 204/238 [00:23<00:03,  9.54it/s]
 87% 206/238 [00:23<00:03,  9.25it/s]
 87% 207/238 [00:24<00:03,  8.75it/s]
 87% 208/238 [00:24<00:03,  8.28it/s]
 88% 209/238 [00:24<00:03,  8.49it/s]
 88% 210/238 [00:24<00:03,  8.05it/s]
 89% 211/238 [00:24<00:03,  7.95it/s]
 89% 212/238 [00:24<00:03,  7.62it/s]
 89% 213/238 [00:24<00:03,  7.45it/s]
 90% 214/238 [00:24<00:03,  7.29it/s]
 90% 215/238 [00:25<00:03,  7.21it/s]
 91% 217/238 [00:25<00:02,  8.62it/s]
 92% 218/238 [00:25<00:02,  8.14it/s]
 92% 219/238 [00:25<00:02,  7.80it/s]
 92% 220/238 [00:25<00:02,  7.78it/s]
 93% 221/238 [00:25<00:02,  7.64it/s]
 94% 223/238 [00:26<00:01,  9.17it/s]
 94% 224/238 [00:26<00:01,  9.19it/s]
 95% 225/238 [00:26<00:01,  9.11it/s]
 95% 226/238 [00:26<00:01,  9.05it/s]
 95% 227/238 [00:26<00:01,  8.87it/s]
 96% 229/238 [00:26<00:00,  9.84it/s]
 97% 230/238 [00:26<00:00,  9.23it/s]
 97% 232/238 [00:27<00:00,  9.10it/s]
 98% 233/238 [00:27<00:00,  9.01it/s]
 99% 235/238 [00:27<00:00,  9.30it/s]
 99% 236/238 [00:27<00:00,  8.87it/s]

{'eval_loss': 0.49943801760673523, 'eval_accuracy': 0.8188157894736842, 'eval_macro_f1': 0.8164152975113501, 'eval_runtime': 27.7368, 'eval_samples_per_second': 274.004, 'eval_steps_per_second': 8.581, 'epoch': 1.0}
 33% 3188/9564 [05:38<08:41, 12.22it/s]
100% 238/238 [00:27<00:00, 10.40it/s]
{'loss': 0.1877, 'grad_norm': 0.9417132139205933, 'learning_rate': 1.3308239230447513e-05, 'epoch': 1.0}
{'loss': 0.1844, 'grad_norm': 1.8543857336044312, 'learning_rate': 1.3203680468423254e-05, 'epoch': 1.02}
{'loss': 0.2275, 'grad_norm': 1.7433573007583618, 'learning_rate': 1.3099121706398999e-05, 'epoch': 1.04}
{'loss': 0.1788, 'grad_norm': 1.5282344818115234, 'learning_rate': 1.299456294437474e-05, 'epoch': 1.05}
{'loss': 0.1872, 'grad_norm': 1.3543347120285034, 'learning_rate': 1.2890004182350482e-05, 'epoch': 1.07}
{'loss': 0.1636, 'grad_norm': 1.183306336402893, 'learning_rate': 1.2785445420326223e-05, 'epoch': 1.08}
{'loss': 0.1755, 'grad_norm': 4.798236846923828, 'learning_rate': 1.2680886658301968e-05, 'epoch': 1.1}
{'loss': 0.1913, 'grad_norm': 3.4180595874786377, 'learning_rate': 1.2576327896277709e-05, 'epoch': 1.11}
{'loss': 0.1581, 'grad_norm': 3.700512170791626, 'learning_rate': 1.2471769134253452e-05, 'epoch': 1.13}
{'loss': 0.2275, 'grad_norm': 2.3735849857330322, 'learning_rate': 1.2367210372229194e-05, 'epoch': 1.14}
{'loss': 0.1817, 'grad_norm': 1.9705345630645752, 'learning_rate': 1.2262651610204937e-05, 'epoch': 1.16}
{'loss': 0.177, 'grad_norm': 3.001173973083496, 'learning_rate': 1.2158092848180678e-05, 'epoch': 1.18}
{'loss': 0.2066, 'grad_norm': 0.7788540720939636, 'learning_rate': 1.2053534086156419e-05, 'epoch': 1.19}
{'loss': 0.1848, 'grad_norm': 1.6514612436294556, 'learning_rate': 1.1948975324132164e-05, 'epoch': 1.21}
{'loss': 0.1841, 'grad_norm': 1.1580864191055298, 'learning_rate': 1.1844416562107906e-05, 'epoch': 1.22}
{'loss': 0.2014, 'grad_norm': 0.3143901526927948, 'learning_rate': 1.1739857800083647e-05, 'epoch': 1.24}
{'loss': 0.1704, 'grad_norm': 0.4397544264793396, 'learning_rate': 1.1635299038059392e-05, 'epoch': 1.25}
{'loss': 0.2033, 'grad_norm': 1.7475059032440186, 'learning_rate': 1.1530740276035133e-05, 'epoch': 1.27}
{'loss': 0.1677, 'grad_norm': 2.915116548538208, 'learning_rate': 1.1426181514010874e-05, 'epoch': 1.29}
{'loss': 0.1754, 'grad_norm': 1.0955497026443481, 'learning_rate': 1.1321622751986618e-05, 'epoch': 1.3}
{'loss': 0.1317, 'grad_norm': 2.0319900512695312, 'learning_rate': 1.121706398996236e-05, 'epoch': 1.32}
{'loss': 0.2056, 'grad_norm': 2.0405287742614746, 'learning_rate': 1.1112505227938102e-05, 'epoch': 1.33}
{'loss': 0.1827, 'grad_norm': 2.0796356201171875, 'learning_rate': 1.1007946465913843e-05, 'epoch': 1.35}
{'loss': 0.1448, 'grad_norm': 3.48117733001709, 'learning_rate': 1.0903387703889588e-05, 'epoch': 1.36}
{'loss': 0.1704, 'grad_norm': 1.6187423467636108, 'learning_rate': 1.0798828941865329e-05, 'epoch': 1.38}
{'loss': 0.1476, 'grad_norm': 0.5000677704811096, 'learning_rate': 1.0694270179841071e-05, 'epoch': 1.4}
{'loss': 0.2169, 'grad_norm': 1.8750337362289429, 'learning_rate': 1.0589711417816814e-05, 'epoch': 1.41}
{'loss': 0.1768, 'grad_norm': 1.606414556503296, 'learning_rate': 1.0485152655792557e-05, 'epoch': 1.43}
{'loss': 0.1693, 'grad_norm': 2.5342345237731934, 'learning_rate': 1.0380593893768298e-05, 'epoch': 1.44}
{'loss': 0.1626, 'grad_norm': 0.19634677469730377, 'learning_rate': 1.027603513174404e-05, 'epoch': 1.46}
{'loss': 0.1672, 'grad_norm': 2.0778963565826416, 'learning_rate': 1.0171476369719783e-05, 'epoch': 1.47}
{'loss': 0.211, 'grad_norm': 3.35870361328125, 'learning_rate': 1.0066917607695526e-05, 'epoch': 1.49}
{'loss': 0.18, 'grad_norm': 2.606971263885498, 'learning_rate': 9.962358845671269e-06, 'epoch': 1.51}
{'loss': 0.1836, 'grad_norm': 1.5833133459091187, 'learning_rate': 9.85780008364701e-06, 'epoch': 1.52}
{'loss': 0.1807, 'grad_norm': 2.1515820026397705, 'learning_rate': 9.753241321622753e-06, 'epoch': 1.54}
{'loss': 0.1682, 'grad_norm': 0.7736573219299316, 'learning_rate': 9.648682559598495e-06, 'epoch': 1.55}
{'loss': 0.1745, 'grad_norm': 1.5740892887115479, 'learning_rate': 9.544123797574238e-06, 'epoch': 1.57}
{'loss': 0.1877, 'grad_norm': 1.6342742443084717, 'learning_rate': 9.43956503554998e-06, 'epoch': 1.58}
{'loss': 0.1758, 'grad_norm': 2.8300020694732666, 'learning_rate': 9.335006273525722e-06, 'epoch': 1.6}
{'loss': 0.1905, 'grad_norm': 3.628993511199951, 'learning_rate': 9.230447511501465e-06, 'epoch': 1.62}
{'loss': 0.1876, 'grad_norm': 0.6175102591514587, 'learning_rate': 9.125888749477207e-06, 'epoch': 1.63}
{'loss': 0.1575, 'grad_norm': 0.49188491702079773, 'learning_rate': 9.02132998745295e-06, 'epoch': 1.65}
{'loss': 0.2025, 'grad_norm': 0.8081086874008179, 'learning_rate': 8.916771225428693e-06, 'epoch': 1.66}
{'loss': 0.1855, 'grad_norm': 1.211049199104309, 'learning_rate': 8.812212463404434e-06, 'epoch': 1.68}
{'loss': 0.181, 'grad_norm': 0.9561715722084045, 'learning_rate': 8.707653701380176e-06, 'epoch': 1.69}
{'loss': 0.1935, 'grad_norm': 2.9795966148376465, 'learning_rate': 8.603094939355918e-06, 'epoch': 1.71}
{'loss': 0.177, 'grad_norm': 0.43379759788513184, 'learning_rate': 8.49853617733166e-06, 'epoch': 1.73}
{'loss': 0.1985, 'grad_norm': 3.7057745456695557, 'learning_rate': 8.393977415307403e-06, 'epoch': 1.74}
{'loss': 0.1504, 'grad_norm': 1.8560349941253662, 'learning_rate': 8.289418653283146e-06, 'epoch': 1.76}

In [16]:
!python ag_news_project.py --error-analysis

Train size: 51000 | Test size: 7600
label
0    30000
1    15000
2     4500
3     1500
Name: count, dtype: int64
[error analysis] most common confusions:
true_label  pred_label
Sci/Tech    Business      237
            World         204
Business    World         142
            Sci/Tech       79
Sci/Tech    Sports         19
Sports      World          18
World       Business       17
Business    Sports         14
World       Sports          9
Sports      Business        5
dtype: int64
Summary written to outputs/summary_report.md

In [17]:
!ls -lh outputs/

total 44K
-rw-r--r-- 1 root root 1.1K Aug 14 20:56 baseline_report.json
-rw-r--r-- 1 root root 8.6K Aug 14 21:42 error_analysis.csv
-rw-r--r-- 1 root root  245 Aug 14 21:42 error_confusion_pairs.csv
-rw-r--r-- 1 root root 1.3K Aug 14 21:23 full_finetune_report.json
drwxr-xr-x 3 root root 4.0K Aug 14 21:23 full_run
-rw-r--r-- 1 root root 1.3K Aug 14 21:42 lora_finetune_report.json
drwxr-xr-x 3 root root 4.0K Aug 14 21:42 lora_run
-rw-r--r-- 1 root root 5.8K Aug 14 21:42 summary_report.md

In [20]:
%cd /content/ag-news-project

/content/ag-news-project

In [25]:
%cd /content/ag-news-project
!find outputs -maxdepth 3 -type f -printf "%p\n"

/content/ag-news-project
outputs/summary_report.md
outputs/full_finetune_report.json
outputs/full_run/final_model/tokenizer_config.json
outputs/full_run/final_model/model.safetensors
outputs/full_run/final_model/vocab.txt
outputs/full_run/final_model/training_args.bin
outputs/full_run/final_model/tokenizer.json
outputs/full_run/final_model/special_tokens_map.json
outputs/full_run/final_model/config.json
outputs/error_confusion_pairs.csv
outputs/baseline_report.json
outputs/error_analysis.csv
outputs/lora_run/final_model/tokenizer_config.json
outputs/lora_run/final_model/README.md
outputs/lora_run/final_model/vocab.txt
outputs/lora_run/final_model/training_args.bin
outputs/lora_run/final_model/adapter_config.json
outputs/lora_run/final_model/tokenizer.json
outputs/lora_run/final_model/special_tokens_map.json
outputs/lora_run/final_model/adapter_model.safetensors
outputs/lora_finetune_report.json

In [ ]:

!pip uninstall -y numpy pandas
!pip install numpy==1.26.4 pandas==2.2.2

Found existing installation: numpy 1.26.4
Uninstalling numpy-1.26.4:
  Successfully uninstalled numpy-1.26.4
Found existing installation: pandas 2.2.2
Uninstalling pandas-2.2.2:
  Successfully uninstalled pandas-2.2.2
Collecting numpy==1.26.4
  Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
Collecting pandas==2.2.2
  Using cached pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (19 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2026.3.post1)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas==2.2.2) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas==2.2.2) (1.17.0)
Using cached numpy-1.26.4-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.0 MB)
Using cached pandas-2.2.2-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.7 MB)
Installing collected packages: numpy, pandas
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
torchvision 0.26.0+cu128 requires torch==2.11.0, but you have torch 2.3.1 which is incompatible.
gradio 6.20.0 requires huggingface-hub<2.0,>=1.2.0, but you have huggingface-hub 0.36.2 which is incompatible.
tifffile 2026.4.11 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jax 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-contrib-python 4.13.0.92 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
hdbscan 0.8.44 requires scikit-learn>=1.6, but you have scikit-learn 1.5.1 which is incompatible.
rasterio 1.5.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
opencv-python-headless 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
shap 0.52.0 requires numpy>=2, but you have numpy 1.26.4 which is incompatible.
umap-learn 0.5.12 requires scikit-learn>=1.6, but you have scikit-learn 1.5.1 which is incompatible.
xarray-einstats 0.10.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
jaxlib 0.7.2 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
cupy-cuda12x 14.0.1 requires numpy<2.6,>=2.0, but you have numpy 1.26.4 which is incompatible.
tobler 0.14.0 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
pytensor 2.38.3 requires numpy>=2.0, but you have numpy 1.26.4 which is incompatible.
opencv-python 5.0.0.93 requires numpy>=2; python_version >= "3.9", but you have numpy 1.26.4 which is incompatible.
Successfully installed numpy-1.26.4 pandas-2.2.2

In [1]:
import pandas as pd

In [2]:
%cd /content/ag-news-project

/content/ag-news-project

In [3]:
!ls -lh outputs/error_analysis.csv outputs/error_confusion_pairs.csv

-rw-r--r-- 1 root root 8.6K Aug 14 21:42 outputs/error_analysis.csv
-rw-r--r-- 1 root root  245 Aug 14 21:42 outputs/error_confusion_pairs.csv

In [4]:
import pandas as pd
errors = pd.read_csv("outputs/error_analysis.csv")
errors.head(20)

,text,true_label,pred_label,confidence
0,Indonesian diplomats asked to help improve RI ...,Business,World,0.999847
1,World briefs LONDON - A man wielding a machete...,Business,World,0.999846
2,Philippines mourns dead in Russian school sieg...,Sci/Tech,World,0.999839
3,Serial HIV Assault Verdict Expected Mon. (AP) ...,Sci/Tech,World,0.999809
4,Israel to close Erez industrial zone before Ma...,Business,World,0.999795
5,Bush Scraps Most U.S. Sanctions on Libya (Reut...,Sci/Tech,World,0.999788
6,Another homicide in Holland It is a sad day. ...,Sci/Tech,World,0.999787
7,Bryant Makes First Appearance at Trial (AP) AP...,Sci/Tech,Sports,0.999782
8,Special to ESPN.com It #39;s the age old quest...,Business,Sports,0.999777
9,"French Take Gold, Bronze in Single Kayak ATHEN...",Sports,World,0.999750
10,"Groups Eager to Meet With Bush, Kerry (AP) AP ...",Sci/Tech,World,0.999732
11,EU foreign ministers hope to break deadlock ov...,Business,World,0.999724
12,R.I.P. Gary Webb -- Unembedded Reporter The fi...,Sci/Tech,World,0.999719
13,Russia May Ratify Kyoto Protocol in Oct. -- Mi...,Sci/Tech,World,0.999697
14,World #39;s #39;worst plunderers #39; named H...,Sci/Tech,World,0.999685
15,JFK killing fades in intensity WASHINGTON: The...,Sci/Tech,World,0.999673
16,Iran shuts reformist websites WEBSITES CLOSE t...,Sci/Tech,World,0.999668
17,Sandia Motor Speedway for Sale on eBay (AP) AP...,Sci/Tech,Sports,0.999662
18,EU increases pressure for rights in Myanmar EU...,Business,World,0.999640
19,Bea Arthur for President Bea Arthur sparked a ...,Sci/Tech,World,0.999634

In [5]:
pairs = pd.read_csv("outputs/error_confusion_pairs.csv")
pairs

   true_label pred_label    0
0    Sci/Tech   Business  237
1    Sci/Tech      World  204
2    Business      World  142
3    Business   Sci/Tech   79
4    Sci/Tech     Sports   19
5      Sports      World   18
6       World   Business   17
7    Business     Sports   14
8       World     Sports    9
9      Sports   Business    5
10      World   Sci/Tech    5
11     Sports   Sci/Tech    1

In [6]:
!python ag_news_project.py --bayes-correction

Train size: 51000 | Test size: 7600
label
0    30000
1    15000
2     4500
3     1500
Name: count, dtype: int64
2026-08-14 21:52:31.984157: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[bayes] train_only size: 45900
label
0    27000
1    13500
2     4050
3     1350
Name: count, dtype: int64
[bayes] val size: 5100
label
0    3000
1    1500
2     450
3     150
Name: count, dtype: int64
Map: 100% 45900/45900 [00:09<00:00, 4730.59 examples/s]
Map: 100% 5100/5100 [00:00<00:00, 5792.99 examples/s]
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
{'loss': 0.7353, 'grad_norm': 3.9143269062042236, 'learning_rate': 1.9883815499012434e-05, 'epoch': 0.02}
{'loss': 0.3054, 'grad_norm': 3.237093687057495, 'learning_rate': 1.9767630998024863e-05, 'epoch': 0.03}
{'loss': 0.2459, 'grad_norm': 0.346701055765152, 'learning_rate': 1.9651446497037296e-05, 'epoch': 0.05}
{'loss': 0.3052, 'grad_norm': 1.258677363395691, 'learning_rate': 1.9535261996049728e-05, 'epoch': 0.07}
{'loss': 0.2426, 'grad_norm': 3.619293689727783, 'learning_rate': 1.941907749506216e-05, 'epoch': 0.09}
{'loss': 0.1747, 'grad_norm': 2.8869497776031494, 'learning_rate': 1.930289299407459e-05, 'epoch': 0.1}
{'loss': 0.2128, 'grad_norm': 1.029219388961792, 'learning_rate': 1.9186708493087022e-05, 'epoch': 0.12}
{'loss': 0.1678, 'grad_norm': 4.139801979064941, 'learning_rate': 1.9070523992099455e-05, 'epoch': 0.14}
{'loss': 0.2229, 'grad_norm': 8.843207359313965, 'learning_rate': 1.8954339491111887e-05, 'epoch': 0.16}
{'loss': 0.2174, 'grad_norm': 7.207521915435791, 'learning_rate': 1.883815499012432e-05, 'epoch': 0.17}
{'loss': 0.1515, 'grad_norm': 3.1938369274139404, 'learning_rate': 1.8721970489136752e-05, 'epoch': 0.19}
{'loss': 0.1023, 'grad_norm': 17.452239990234375, 'learning_rate': 1.8605785988149185e-05, 'epoch': 0.21}
{'loss': 0.1924, 'grad_norm': 8.678569793701172, 'learning_rate': 1.8489601487161614e-05, 'epoch': 0.23}
{'loss': 0.225, 'grad_norm': 1.5256201028823853, 'learning_rate': 1.8373416986174046e-05, 'epoch': 0.24}
{'loss': 0.178, 'grad_norm': 0.6792280673980713, 'learning_rate': 1.825723248518648e-05, 'epoch': 0.26}
{'loss': 0.1597, 'grad_norm': 2.624979019165039, 'learning_rate': 1.8141047984198908e-05, 'epoch': 0.28}
{'loss': 0.1782, 'grad_norm': 3.2489190101623535, 'learning_rate': 1.802486348321134e-05, 'epoch': 0.3}
{'loss': 0.2235, 'grad_norm': 7.453137397766113, 'learning_rate': 1.7908678982223773e-05, 'epoch': 0.31}
{'loss': 0.1676, 'grad_norm': 4.087256908416748, 'learning_rate': 1.7792494481236205e-05, 'epoch': 0.33}
{'loss': 0.1698, 'grad_norm': 1.9240875244140625, 'learning_rate': 1.7676309980248635e-05, 'epoch': 0.35}
{'loss': 0.1695, 'grad_norm': 2.384517192840576, 'learning_rate': 1.7560125479261067e-05, 'epoch': 0.37}
{'loss': 0.1574, 'grad_norm': 0.22689470648765564, 'learning_rate': 1.74439409782735e-05, 'epoch': 0.38}
{'loss': 0.1771, 'grad_norm': 5.536107540130615, 'learning_rate': 1.7327756477285932e-05, 'epoch': 0.4}
{'loss': 0.1512, 'grad_norm': 0.8753130435943604, 'learning_rate': 1.721157197629836e-05, 'epoch': 0.42}
{'loss': 0.1137, 'grad_norm': 5.038328647613525, 'learning_rate': 1.7095387475310794e-05, 'epoch': 0.44}
{'loss': 0.2008, 'grad_norm': 2.5655791759490967, 'learning_rate': 1.6979202974323226e-05, 'epoch': 0.45}
{'loss': 0.1184, 'grad_norm': 0.08600856363773346, 'learning_rate': 1.686301847333566e-05, 'epoch': 0.47}
{'loss': 0.1245, 'grad_norm': 0.10774233937263489, 'learning_rate': 1.674683397234809e-05, 'epoch': 0.49}
{'loss': 0.1652, 'grad_norm': 1.0463876724243164, 'learning_rate': 1.6630649471360524e-05, 'epoch': 0.51}
{'loss': 0.1562, 'grad_norm': 2.964351177215576, 'learning_rate': 1.6514464970372953e-05, 'epoch': 0.52}
{'loss': 0.1608, 'grad_norm': 0.24788017570972443, 'learning_rate': 1.6398280469385385e-05, 'epoch': 0.54}
{'loss': 0.1625, 'grad_norm': 1.223034381866455, 'learning_rate': 1.6282095968397818e-05, 'epoch': 0.56}
{'loss': 0.1845, 'grad_norm': 0.31024473905563354, 'learning_rate': 1.616591146741025e-05, 'epoch': 0.58}
{'loss': 0.1224, 'grad_norm': 0.21327930688858032, 'learning_rate': 1.604972696642268e-05, 'epoch': 0.59}
{'loss': 0.1303, 'grad_norm': 4.255692481994629, 'learning_rate': 1.5933542465435112e-05, 'epoch': 0.61}
{'loss': 0.1288, 'grad_norm': 7.509098529815674, 'learning_rate': 1.5817357964447544e-05, 'epoch': 0.63}
{'loss': 0.1646, 'grad_norm': 18.128280639648438, 'learning_rate': 1.5701173463459977e-05, 'epoch': 0.64}
{'loss': 0.1423, 'grad_norm': 6.900594234466553, 'learning_rate': 1.5584988962472406e-05, 'epoch': 0.66}
{'loss': 0.1338, 'grad_norm': 0.3840961754322052, 'learning_rate': 1.5468804461484838e-05, 'epoch': 0.68}
{'loss': 0.1236, 'grad_norm': 0.026466142386198044, 'learning_rate': 1.535261996049727e-05, 'epoch': 0.7}
{'loss': 0.1775, 'grad_norm': 10.568713188171387, 'learning_rate': 1.5236435459509702e-05, 'epoch': 0.71}
{'loss': 0.129, 'grad_norm': 0.2690724730491638, 'learning_rate': 1.5120250958522134e-05, 'epoch': 0.73}
{'loss': 0.1821, 'grad_norm': 3.409919023513794, 'learning_rate': 1.5004066457534565e-05, 'epoch': 0.75}
{'loss': 0.1323, 'grad_norm': 4.436378002166748, 'learning_rate': 1.4887881956546997e-05, 'epoch': 0.77}
{'loss': 0.126, 'grad_norm': 11.18105411529541, 'learning_rate': 1.477169745555943e-05, 'epoch': 0.78}
{'loss': 0.1329, 'grad_norm': 10.356962203979492, 'learning_rate': 1.4655512954571862e-05, 'epoch': 0.8}
{'loss': 0.1559, 'grad_norm': 1.6484363079071045, 'learning_rate': 1.4539328453584293e-05, 'epoch': 0.82}
{'loss': 0.1938, 'grad_norm': 12.013338088989258, 'learning_rate': 1.4423143952596726e-05, 'epoch': 0.84}
{'loss': 0.1764, 'grad_norm': 2.3946197032928467, 'learning_rate': 1.4306959451609156e-05, 'epoch': 0.85}
{'loss': 0.1137, 'grad_norm': 3.542753219604492, 'learning_rate': 1.4190774950621589e-05, 'epoch': 0.87}
{'loss': 0.0915, 'grad_norm': 3.3658010959625244, 'learning_rate': 1.407459044963402e-05, 'epoch': 0.89}
{'loss': 0.1671, 'grad_norm': 3.8907089233398438, 'learning_rate': 1.3958405948646452e-05, 'epoch': 0.91}
{'loss': 0.1453, 'grad_norm': 6.249330043792725, 'learning_rate': 1.3842221447658883e-05, 'epoch': 0.92}
{'loss': 0.1414, 'grad_norm': 1.4804003238677979, 'learning_rate': 1.3726036946671315e-05, 'epoch': 0.94}
{'loss': 0.1513, 'grad_norm': 6.1858625411987305, 'learning_rate': 1.3609852445683746e-05, 'epoch': 0.96}
{'loss': 0.1259, 'grad_norm': 0.16172674298286438, 'learning_rate': 1.3493667944696179e-05, 'epoch': 0.98}
{'loss': 0.1356, 'grad_norm': 13.339349746704102, 'learning_rate': 1.337748344370861e-05, 'epoch': 0.99}
 33% 2869/8607 [06:59<12:15,  7.80it/s]
  0% 0/160 [00:00<?, ?it/s]
  2% 3/160 [00:00<00:09, 17.08it/s]
  3% 5/160 [00:00<00:13, 11.31it/s]
  4% 7/160 [00:00<00:16,  9.12it/s]
  5% 8/160 [00:00<00:17,  8.58it/s]
  6% 10/160 [00:01<00:16,  9.25it/s]
  7% 11/160 [00:01<00:15,  9.37it/s]
  8% 13/160 [00:01<00:15,  9.60it/s]
  9% 14/160 [00:01<00:15,  9.44it/s]
 10% 16/160 [00:01<00:14,  9.89it/s]
 11% 17/160 [00:01<00:14,  9.80it/s]
 12% 19/160 [00:01<00:14,  9.67it/s]
 12% 20/160 [00:02<00:15,  9.13it/s]
 14% 22/160 [00:02<00:14,  9.81it/s]
 14% 23/160 [00:02<00:14,  9.50it/s]
 15% 24/160 [00:02<00:14,  9.07it/s]
 16% 25/160 [00:02<00:15,  8.59it/s]
 17% 27/160 [00:02<00:14,  9.34it/s]
 18% 29/160 [00:02<00:12, 10.19it/s]
 19% 30/160 [00:03<00:12, 10.02it/s]
 19% 31/160 [00:03<00:12,  9.94it/s]
 20% 32/160 [00:03<00:14,  9.13it/s]
 21% 33/160 [00:03<00:14,  8.85it/s]
 22% 35/160 [00:03<00:14,  8.88it/s]
 22% 36/160 [00:03<00:14,  8.53it/s]
 24% 38/160 [00:04<00:13,  9.05it/s]
 24% 39/160 [00:04<00:14,  8.59it/s]
 25% 40/160 [00:04<00:14,  8.33it/s]
 26% 42/160 [00:04<00:13,  8.98it/s]
 27% 43/160 [00:04<00:13,  8.73it/s]
 28% 44/160 [00:04<00:12,  8.97it/s]
 28% 45/160 [00:04<00:12,  8.97it/s]
 29% 47/160 [00:04<00:11, 10.09it/s]
 31% 49/160 [00:05<00:11,  9.80it/s]
 31% 50/160 [00:05<00:11,  9.69it/s]
 32% 52/160 [00:05<00:11,  9.66it/s]
 34% 54/160 [00:05<00:10, 10.28it/s]
 35% 56/160 [00:05<00:11,  9.23it/s]
 36% 58/160 [00:06<00:10, 10.08it/s]
 38% 60/160 [00:06<00:10,  9.12it/s]
 39% 62/160 [00:06<00:10,  8.97it/s]
 40% 64/160 [00:06<00:10,  9.59it/s]
 41% 65/160 [00:06<00:10,  9.07it/s]
 42% 67/160 [00:07<00:10,  8.90it/s]
 42% 68/160 [00:07<00:10,  8.67it/s]
 43% 69/160 [00:07<00:10,  8.52it/s]
 44% 70/160 [00:07<00:11,  8.15it/s]
 44% 71/160 [00:07<00:11,  8.07it/s]
 45% 72/160 [00:07<00:10,  8.31it/s]
 46% 74/160 [00:07<00:09,  8.62it/s]
 47% 75/160 [00:08<00:09,  8.76it/s]
 48% 76/160 [00:08<00:09,  8.98it/s]
 49% 78/160 [00:08<00:08, 10.15it/s]
 50% 80/160 [00:08<00:07, 10.55it/s]
 51% 82/160 [00:08<00:07, 10.23it/s]
 52% 84/160 [00:08<00:07, 10.49it/s]
 54% 86/160 [00:09<00:06, 10.92it/s]
 55% 88/160 [00:09<00:07,  9.73it/s]
 56% 89/160 [00:09<00:07,  9.26it/s]
 57% 91/160 [00:09<00:07,  9.23it/s]
 58% 93/160 [00:09<00:06,  9.88it/s]
 59% 94/160 [00:10<00:07,  9.17it/s]
 59% 95/160 [00:10<00:07,  8.88it/s]
 60% 96/160 [00:10<00:07,  8.38it/s]
 61% 97/160 [00:10<00:07,  8.36it/s]
 61% 98/160 [00:10<00:07,  8.64it/s]
 62% 99/160 [00:10<00:07,  8.29it/s]
 62% 100/160 [00:10<00:07,  8.08it/s]
 63% 101/160 [00:10<00:07,  7.90it/s]
 64% 103/160 [00:11<00:06,  9.35it/s]
 66% 105/160 [00:11<00:05, 10.30it/s]
 67% 107/160 [00:11<00:05,  9.25it/s]
 68% 108/160 [00:11<00:05,  8.82it/s]
 68% 109/160 [00:11<00:06,  8.49it/s]
 69% 110/160 [00:11<00:06,  8.31it/s]
 70% 112/160 [00:12<00:05,  8.60it/s]
 71% 114/160 [00:12<00:05,  8.90it/s]
 72% 115/160 [00:12<00:05,  8.96it/s]
 73% 117/160 [00:12<00:04,  9.59it/s]
 74% 118/160 [00:12<00:04,  9.08it/s]
 75% 120/160 [00:12<00:03, 10.05it/s]
 76% 122/160 [00:13<00:03, 10.13it/s]
 78% 124/160 [00:13<00:03, 10.23it/s]
 79% 126/160 [00:13<00:03, 10.04it/s]
 80% 128/160 [00:13<00:03,  9.74it/s]
 81% 130/160 [00:13<00:02, 10.12it/s]
 82% 132/160 [00:14<00:02,  9.54it/s]
 83% 133/160 [00:14<00:02,  9.50it/s]
 84% 134/160 [00:14<00:02,  9.42it/s]
 84% 135/160 [00:14<00:02,  8.98it/s]
 85% 136/160 [00:14<00:02,  9.03it/s]
 86% 137/160 [00:14<00:02,  9.01it/s]
 86% 138/160 [00:14<00:02,  9.06it/s]
 88% 140/160 [00:15<00:02,  9.49it/s]
 89% 142/160 [00:15<00:01, 10.19it/s]
 90% 144/160 [00:15<00:01, 10.77it/s]
 91% 146/160 [00:15<00:01, 10.21it/s]
 92% 148/160 [00:15<00:01, 10.29it/s]
 94% 150/160 [00:15<00:01,  9.82it/s]
 94% 151/160 [00:16<00:00,  9.70it/s]
 95% 152/160 [00:16<00:00,  9.74it/s]
 96% 153/160 [00:16<00:00,  9.51it/s]
 97% 155/160 [00:16<00:00,  9.78it/s]
 98% 156/160 [00:16<00:00,  9.68it/s]
 99% 158/160 [00:16<00:00, 10.66it/s]

{'eval_loss': 0.1342616230249405, 'eval_accuracy': 0.962156862745098, 'eval_macro_f1': 0.8919927603087078, 'eval_runtime': 17.0575, 'eval_samples_per_second': 298.989, 'eval_steps_per_second': 9.38, 'epoch': 1.0}
 33% 2869/8607 [07:16<12:15,  7.80it/s]
100% 160/160 [00:16<00:00, 10.94it/s]
{'loss': 0.0882, 'grad_norm': 2.9781582355499268, 'learning_rate': 1.3261298942721042e-05, 'epoch': 1.01}
{'loss': 0.0915, 'grad_norm': 0.041119981557130814, 'learning_rate': 1.3145114441733473e-05, 'epoch': 1.03}
{'loss': 0.0716, 'grad_norm': 0.13830415904521942, 'learning_rate': 1.3028929940745905e-05, 'epoch': 1.05}
{'loss': 0.0759, 'grad_norm': 4.805585861206055, 'learning_rate': 1.2912745439758336e-05, 'epoch': 1.06}
{'loss': 0.0968, 'grad_norm': 5.887775421142578, 'learning_rate': 1.279656093877077e-05, 'epoch': 1.08}
{'loss': 0.0796, 'grad_norm': 4.8752827644348145, 'learning_rate': 1.2680376437783201e-05, 'epoch': 1.1}
{'loss': 0.0664, 'grad_norm': 0.024393025785684586, 'learning_rate': 1.2564191936795634e-05, 'epoch': 1.12}
{'loss': 0.0749, 'grad_norm': 0.8097678422927856, 'learning_rate': 1.2448007435808064e-05, 'epoch': 1.13}
{'loss': 0.0883, 'grad_norm': 0.9957805871963501, 'learning_rate': 1.2331822934820497e-05, 'epoch': 1.15}
{'loss': 0.1235, 'grad_norm': 0.12515977025032043, 'learning_rate': 1.2215638433832928e-05, 'epoch': 1.17}
{'loss': 0.0989, 'grad_norm': 0.09062206745147705, 'learning_rate': 1.209945393284536e-05, 'epoch': 1.19}
{'loss': 0.0906, 'grad_norm': 2.703712224960327, 'learning_rate': 1.1983269431857791e-05, 'epoch': 1.2}
{'loss': 0.0904, 'grad_norm': 0.0490601547062397, 'learning_rate': 1.1867084930870223e-05, 'epoch': 1.22}
{'loss': 0.0564, 'grad_norm': 0.06970905512571335, 'learning_rate': 1.1750900429882654e-05, 'epoch': 1.24}
{'loss': 0.1339, 'grad_norm': 0.29821738600730896, 'learning_rate': 1.1634715928895087e-05, 'epoch': 1.25}
{'loss': 0.0778, 'grad_norm': 0.1964339017868042, 'learning_rate': 1.1518531427907518e-05, 'epoch': 1.27}
{'loss': 0.0954, 'grad_norm': 1.7163294553756714, 'learning_rate': 1.140234692691995e-05, 'epoch': 1.29}
{'loss': 0.109, 'grad_norm': 3.8927018642425537, 'learning_rate': 1.128616242593238e-05, 'epoch': 1.31}
{'loss': 0.0976, 'grad_norm': 0.3287034332752228, 'learning_rate': 1.1169977924944813e-05, 'epoch': 1.32}
{'loss': 0.0833, 'grad_norm': 2.0392942428588867, 'learning_rate': 1.1053793423957244e-05, 'epoch': 1.34}
{'loss': 0.132, 'grad_norm': 0.06693809479475021, 'learning_rate': 1.0937608922969677e-05, 'epoch': 1.36}
{'loss': 0.0551, 'grad_norm': 0.10173701494932175, 'learning_rate': 1.0821424421982107e-05, 'epoch': 1.38}
{'loss': 0.0947, 'grad_norm': 6.314187526702881, 'learning_rate': 1.0705239920994542e-05, 'epoch': 1.39}
{'loss': 0.0818, 'grad_norm': 6.709192752838135, 'learning_rate': 1.0589055420006972e-05, 'epoch': 1.41}
{'loss': 0.0936, 'grad_norm': 3.5923478603363037, 'learning_rate': 1.0472870919019405e-05, 'epoch': 1.43}
{'loss': 0.0724, 'grad_norm': 0.054862093180418015, 'learning_rate': 1.0356686418031836e-05, 'epoch': 1.45}
{'loss': 0.0818, 'grad_norm': 6.551200866699219, 'learning_rate': 1.0240501917044268e-05, 'epoch': 1.46}
{'loss': 0.0821, 'grad_norm': 4.737439155578613, 'learning_rate': 1.0124317416056699e-05, 'epoch': 1.48}
{'loss': 0.1302, 'grad_norm': 0.23811061680316925, 'learning_rate': 1.0008132915069131e-05, 'epoch': 1.5}
{'loss': 0.0906, 'grad_norm': 0.7406378984451294, 'learning_rate': 9.891948414081562e-06, 'epoch': 1.52}
{'loss': 0.0791, 'grad_norm': 3.510913133621216, 'learning_rate': 9.775763913093995e-06, 'epoch': 1.53}
{'loss': 0.1368, 'grad_norm': 0.09013199061155319, 'learning_rate': 9.659579412106426e-06, 'epoch': 1.55}
{'loss': 0.1512, 'grad_norm': 14.96020221710205, 'learning_rate': 9.543394911118858e-06, 'epoch': 1.57}
{'loss': 0.0782, 'grad_norm': 8.795004844665527, 'learning_rate': 9.427210410131289e-06, 'epoch': 1.59}
{'loss': 0.1109, 'grad_norm': 3.775890350341797, 'learning_rate': 9.311025909143721e-06, 'epoch': 1.6}
{'loss': 0.0946, 'grad_norm': 0.6890307664871216, 'learning_rate': 9.194841408156154e-06, 'epoch': 1.62}
{'loss': 0.0867, 'grad_norm': 6.177624702453613, 'learning_rate': 9.078656907168585e-06, 'epoch': 1.64}
{'loss': 0.0957, 'grad_norm': 0.5178537964820862, 'learning_rate': 8.962472406181017e-06, 'epoch': 1.66}
{'loss': 0.0821, 'grad_norm': 0.38906222581863403, 'learning_rate': 8.846287905193448e-06, 'epoch': 1.67}
{'loss': 0.1096, 'grad_norm': 0.05119872838258743, 'learning_rate': 8.73010340420588e-06, 'epoch': 1.69}
{'loss': 0.1083, 'grad_norm': 2.0327441692352295, 'learning_rate': 8.613918903218311e-06, 'epoch': 1.71}
{'loss': 0.0464, 'grad_norm': 10.912899017333984, 'learning_rate': 8.497734402230744e-06, 'epoch': 1.73}
{'loss': 0.0731, 'grad_norm': 0.08098555356264114, 'learning_rate': 8.381549901243174e-06, 'epoch': 1.74}
{'loss': 0.0864, 'grad_norm': 0.07398601621389389, 'learning_rate': 8.265365400255605e-06, 'epoch': 1.76}
{'loss': 0.0984, 'grad_norm': 7.180377006530762, 'learning_rate': 8.14918089926804e-06, 'epoch': 1.78}
{'loss': 0.0788, 'grad_norm': 17.491416931152344, 'learning_rate': 8.03299639828047e-06, 'epoch': 1.8}
{'loss': 0.1006, 'grad_norm': 2.6456964015960693, 'learning_rate': 7.916811897292903e-06, 'epoch': 1.81}
{'loss': 0.0948, 'grad_norm': 0.5363132357597351, 'learning_rate': 7.800627396305334e-06, 'epoch': 1.83}
{'loss': 0.0439, 'grad_norm': 0.12908333539962769, 'learning_rate': 7.684442895317766e-06, 'epoch': 1.85}
{'loss': 0.0821, 'grad_norm': 0.12893515825271606, 'learning_rate': 7.568258394330197e-06, 'epoch': 1.86}
{'loss': 0.0986, 'grad_norm': 1.445946455001831, 'learning_rate': 7.4520738933426285e-06, 'epoch': 1.88}
{'loss': 0.0821, 'grad_norm': 0.024186352267861366, 'learning_rate': 7.33588939235506e-06, 'epoch': 1.9}
{'loss': 0.1037, 'grad_norm': 0.02313234843313694, 'learning_rate': 7.219704891367492e-06, 'epoch': 1.92}
{'loss': 0.0881, 'grad_norm': 0.349758505821228, 'learning_rate': 7.103520390379924e-06, 'epoch': 1.93}
{'loss': 0.0855, 'grad_norm': 7.843506336212158, 'learning_rate': 6.987335889392356e-06, 'epoch': 1.95}
{'loss': 0.0713, 'grad_norm': 0.026491494849324226, 'learning_rate': 6.8711513884047875e-06, 'epoch': 1.97}
{'loss': 0.09, 'grad_norm': 0.0659971684217453, 'learning_rate': 6.754966887417219e-06, 'epoch': 1.99}
 67% 5738/8607 [14:25<06:48,  7.02it/s]
  0% 0/160 [00:00<?, ?it/s]
  2% 3/160 [00:00<00:09, 16.67it/s]
  3% 5/160 [00:00<00:13, 11.30it/s]
  4% 7/160 [00:00<00:16,  9.23it/s]
  5% 8/160 [00:00<00:17,  8.64it/s]
  6% 10/160 [00:01<00:16,  9.34it/s]
  7% 11/160 [00:01<00:15,  9.42it/s]
  8% 13/160 [00:01<00:15,  9.62it/s]
  9% 14/160 [00:01<00:15,  9.48it/s]
 10% 16/160 [00:01<00:14,  9.99it/s]
 11% 18/160 [00:01<00:13, 10.36it/s]
 12% 20/160 [00:02<00:14,  9.35it/s]
 14% 22/160 [00:02<00:13,  9.88it/s]
 15% 24/160 [00:02<00:14,  9.38it/s]
 16% 25/160 [00:02<00:14,  9.00it/s]
 17% 27/160 [00:02<00:14,  9.44it/s]
 18% 29/160 [00:02<00:12, 10.32it/s]
 19% 31/160 [00:03<00:12, 10.07it/s]
 21% 33/160 [00:03<00:13,  9.23it/s]
 22% 35/160 [00:03<00:13,  9.15it/s]
 22% 36/160 [00:03<00:14,  8.83it/s]
 24% 38/160 [00:03<00:13,  9.17it/s]
 24% 39/160 [00:04<00:13,  8.70it/s]
 25% 40/160 [00:04<00:14,  8.44it/s]
 26% 42/160 [00:04<00:13,  9.00it/s]
 27% 43/160 [00:04<00:13,  8.70it/s]
 28% 44/160 [00:04<00:12,  8.97it/s]
 28% 45/160 [00:04<00:12,  8.99it/s]
 29% 47/160 [00:04<00:11, 10.03it/s]
 31% 49/160 [00:05<00:11,  9.77it/s]
 31% 50/160 [00:05<00:11,  9.66it/s]
 32% 52/160 [00:05<00:11,  9.63it/s]
 34% 54/160 [00:05<00:10, 10.30it/s]
 35% 56/160 [00:05<00:11,  9.18it/s]
 36% 58/160 [00:06<00:10,  9.95it/s]
 38% 60/160 [00:06<00:11,  8.99it/s]
 38% 61/160 [00:06<00:10,  9.14it/s]
 39% 62/160 [00:06<00:11,  8.73it/s]
 40% 64/160 [00:06<00:10,  9.56it/s]
 41% 65/160 [00:06<00:10,  9.05it/s]
 42% 67/160 [00:07<00:10,  8.86it/s]
 42% 68/160 [00:07<00:10,  8.60it/s]
 43% 69/160 [00:07<00:10,  8.46it/s]
 44% 70/160 [00:07<00:11,  8.06it/s]
 44% 71/160 [00:07<00:11,  8.02it/s]
 45% 72/160 [00:07<00:10,  8.29it/s]
 46% 74/160 [00:07<00:09,  8.61it/s]
 47% 75/160 [00:08<00:09,  8.72it/s]
 48% 76/160 [00:08<00:09,  8.96it/s]
 49% 78/160 [00:08<00:08, 10.01it/s]
 50% 80/160 [00:08<00:07, 10.49it/s]
 51% 82/160 [00:08<00:07, 10.23it/s]
 52% 84/160 [00:08<00:07, 10.43it/s]
 54% 86/160 [00:09<00:06, 10.77it/s]
 55% 88/160 [00:09<00:07,  9.60it/s]
 56% 89/160 [00:09<00:07,  9.14it/s]
 57% 91/160 [00:09<00:07,  9.21it/s]
 58% 93/160 [00:09<00:06,  9.82it/s]
 59% 94/160 [00:10<00:07,  9.13it/s]
 59% 95/160 [00:10<00:07,  8.76it/s]
 60% 96/160 [00:10<00:07,  8.28it/s]
 61% 97/160 [00:10<00:07,  8.24it/s]
 61% 98/160 [00:10<00:07,  8.54it/s]
 62% 99/160 [00:10<00:07,  8.26it/s]
 62% 100/160 [00:10<00:07,  8.04it/s]
 63% 101/160 [00:10<00:07,  7.92it/s]
 64% 103/160 [00:11<00:06,  9.27it/s]
 66% 105/160 [00:11<00:05, 10.29it/s]
 67% 107/160 [00:11<00:05,  9.28it/s]
 68% 108/160 [00:11<00:05,  8.82it/s]

In [ ]:
!python ag_news_project.py --fewshot-curve

Train size: 51000 | Test size: 7600
label
0    30000
1    15000
2     4500
3     1500
Name: count, dtype: int64
2026-08-14 22:16:14.249562: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Map: 100% 510/510 [00:00<00:00, 5025.01 examples/s]
Map: 100% 7600/7600 [00:01<00:00, 5935.13 examples/s]
Some weights of DistilBertForSequenceClassification were not initialized from the model checkpoint at distilbert-base-uncased and are newly initialized: ['classifier.bias', 'classifier.weight', 'pre_classifier.bias', 'pre_classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
 33% 32/96 [00:04<00:08,  7.62it/s]
  0% 0/238 [00:00<?, ?it/s]
  1% 3/238 [00:00<00:17, 13.22it/s]
  2% 5/238 [00:00<00:20, 11.41it/s]
  3% 7/238 [00:00<00:22, 10.16it/s]
  4% 9/238 [00:00<00:24,  9.27it/s]
  4% 10/238 [00:01<00:25,  8.99it/s]
  5% 12/238 [00:01<00:23,  9.44it/s]
  6% 14/238 [00:01<00:23,  9.56it/s]
  6% 15/238 [00:01<00:23,  9.37it/s]
  7% 17/238 [00:01<00:22,  9.84it/s]
  8% 18/238 [00:01<00:23,  9.34it/s]
  8% 20/238 [00:02<00:23,  9.24it/s]
  9% 21/238 [00:02<00:24,  8.98it/s]
 10% 23/238 [00:02<00:22,  9.70it/s]
 10% 24/238 [00:02<00:23,  9.27it/s]
 11% 25/238 [00:02<00:23,  9.00it/s]
 11% 27/238 [00:02<00:21,  9.70it/s]
 12% 28/238 [00:02<00:21,  9.74it/s]
 12% 29/238 [00:03<00:22,  9.44it/s]
 13% 31/238 [00:03<00:22,  9.39it/s]
 13% 32/238 [00:03<00:22,  9.28it/s]
 14% 33/238 [00:03<00:21,  9.45it/s]
 14% 34/238 [00:03<00:22,  9.15it/s]
 15% 35/238 [00:03<00:22,  8.97it/s]
 15% 36/238 [00:03<00:22,  8.87it/s]
 16% 38/238 [00:03<00:19, 10.03it/s]
 16% 39/238 [00:04<00:21,  9.36it/s]
 17% 41/238 [00:04<00:19, 10.07it/s]
 18% 43/238 [00:04<00:18, 10.36it/s]
 19% 45/238 [00:04<00:19, 10.03it/s]
 20% 47/238 [00:04<00:18, 10.45it/s]
 21% 49/238 [00:05<00:17, 11.10it/s]
 21% 51/238 [00:05<00:18, 10.15it/s]
 22% 53/238 [00:05<00:18, 10.25it/s]
 23% 55/238 [00:05<00:18, 10.03it/s]
 24% 57/238 [00:05<00:17, 10.59it/s]
 25% 59/238 [00:06<00:17, 10.14it/s]
 26% 61/238 [00:06<00:18,  9.68it/s]
 26% 62/238 [00:06<00:18,  9.41it/s]
 26% 63/238 [00:06<00:19,  9.16it/s]
 27% 65/238 [00:06<00:17,  9.83it/s]
 28% 66/238 [00:06<00:18,  9.51it/s]
 29% 68/238 [00:06<00:17,  9.91it/s]
 29% 69/238 [00:07<00:17,  9.43it/s]
 30% 71/238 [00:07<00:17,  9.50it/s]
 30% 72/238 [00:07<00:18,  9.19it/s]
 31% 73/238 [00:07<00:18,  8.85it/s]
 31% 74/238 [00:07<00:19,  8.63it/s]
 32% 76/238 [00:07<00:17,  9.11it/s]
 32% 77/238 [00:07<00:17,  8.97it/s]
 33% 79/238 [00:08<00:17,  9.34it/s]
 34% 80/238 [00:08<00:17,  9.06it/s]
 34% 81/238 [00:08<00:17,  8.75it/s]
 35% 83/238 [00:08<00:15, 10.00it/s]
 35% 84/238 [00:08<00:16,  9.58it/s]
 36% 85/238 [00:08<00:16,  9.13it/s]
 37% 87/238 [00:09<00:16,  9.10it/s]
 37% 89/238 [00:09<00:16,  9.30it/s]
 38% 90/238 [00:09<00:16,  8.99it/s]
 39% 92/238 [00:09<00:16,  9.02it/s]
 39% 94/238 [00:09<00:14,  9.98it/s]
 40% 95/238 [00:09<00:14,  9.69it/s]
 41% 97/238 [00:10<00:14,  9.67it/s]
 41% 98/238 [00:10<00:15,  9.30it/s]
 42% 99/238 [00:10<00:15,  8.97it/s]
 42% 101/238 [00:10<00:14,  9.33it/s]
 43% 103/238 [00:10<00:13,  9.64it/s]
 44% 104/238 [00:10<00:14,  9.41it/s]
 44% 105/238 [00:10<00:14,  9.42it/s]
 45% 106/238 [00:11<00:14,  9.40it/s]
 45% 108/238 [00:11<00:12, 10.18it/s]
 46% 109/238 [00:11<00:12,  9.97it/s]
 47% 111/238 [00:11<00:13,  9.76it/s]
 47% 112/238 [00:11<00:13,  9.25it/s]
 47% 113/238 [00:11<00:13,  9.09it/s]
 48% 115/238 [00:12<00:13,  8.88it/s]
 49% 117/238 [00:12<00:12,  9.53it/s]
 50% 118/238 [00:12<00:13,  8.93it/s]
 50% 120/238 [00:12<00:12,  9.25it/s]
 51% 121/238 [00:12<00:13,  8.83it/s]
 52% 123/238 [00:12<00:12,  9.36it/s]
 53% 125/238 [00:13<00:12,  9.29it/s]
 53% 126/238 [00:13<00:12,  8.79it/s]
 54% 128/238 [00:13<00:11,  9.18it/s]
 54% 129/238 [00:13<00:12,  8.87it/s]
 55% 130/238 [00:13<00:12,  8.81it/s]
 55% 132/238 [00:13<00:10, 10.13it/s]
 56% 134/238 [00:14<00:10,  9.52it/s]
 57% 135/238 [00:14<00:11,  9.28it/s]
 57% 136/238 [00:14<00:11,  8.88it/s]
 58% 138/238 [00:14<00:10,  9.25it/s]
 59% 140/238 [00:14<00:10,  9.48it/s]
 59% 141/238 [00:14<00:10,  9.06it/s]
 60% 143/238 [00:15<00:10,  9.34it/s]
 61% 145/238 [00:15<00:09,  9.35it/s]
 61% 146/238 [00:15<00:09,  9.34it/s]
 62% 147/238 [00:15<00:10,  9.00it/s]
 62% 148/238 [00:15<00:10,  8.73it/s]
 63% 150/238 [00:15<00:10,  8.74it/s]
 63% 151/238 [00:15<00:09,  8.93it/s]
 64% 152/238 [00:16<00:09,  8.63it/s]
 65% 154/238 [00:16<00:09,  9.15it/s]
 66% 156/238 [00:16<00:08,  9.66it/s]
 66% 158/238 [00:16<00:07, 10.40it/s]
 67% 160/238 [00:16<00:07, 10.23it/s]
 68% 162/238 [00:17<00:08,  9.24it/s]
 68% 163/238 [00:17<00:08,  8.85it/s]
 69% 164/238 [00:17<00:08,  8.42it/s]
 70% 166/238 [00:17<00:08,  8.61it/s]
 70% 167/238 [00:17<00:08,  8.37it/s]
 71% 168/238 [00:17<00:08,  8.23it/s]
 71% 169/238 [00:18<00:08,  8.01it/s]
 72% 171/238 [00:18<00:08,  8.08it/s]
 73% 173/238 [00:18<00:07,  9.24it/s]
 73% 174/238 [00:18<00:07,  8.89it/s]
 74% 176/238 [00:18<00:06,  8.92it/s]
 74% 177/238 [00:18<00:06,  8.72it/s]
 75% 179/238 [00:19<00:06,  9.06it/s]
 76% 180/238 [00:19<00:06,  8.72it/s]
 76% 181/238 [00:19<00:06,  8.39it/s]
 76% 182/238 [00:19<00:06,  8.56it/s]
 77% 184/238 [00:19<00:05,  9.35it/s]
 78% 185/238 [00:19<00:06,  8.77it/s]
 78% 186/238 [00:19<00:06,  8.41it/s]
 79% 187/238 [00:20<00:06,  8.06it/s]
 79% 188/238 [00:20<00:06,  7.85it/s]
 79% 189/238 [00:20<00:06,  7.74it/s]
 80% 190/238 [00:20<00:06,  7.79it/s]
 81% 192/238 [00:20<00:04,  9.27it/s]
 81% 193/238 [00:20<00:04,  9.42it/s]
 82% 194/238 [00:20<00:04,  9.33it/s]
 82% 196/238 [00:21<00:04, 10.33it/s]
 83% 198/238 [00:21<00:04,  8.89it/s]
 84% 200/238 [00:21<00:04,  9.37it/s]
 84% 201/238 [00:21<00:04,  9.08it/s]
 85% 203/238 [00:21<00:03,  9.73it/s]
 86% 204/238 [00:21<00:03,  9.62it/s]
 87% 206/238 [00:22<00:03,  9.34it/s]
 87% 207/238 [00:22<00:03,  8.84it/s]
 87% 208/238 [00:22<00:03,  8.35it/s]
 88% 209/238 [00:22<00:03,  8.68it/s]
 88% 210/238 [00:22<00:03,  8.24it/s]
 89% 211/238 [00:22<00:03,  8.18it/s]
 89% 212/238 [00:22<00:03,  7.80it/s]
 89% 213/238 [00:23<00:03,  7.58it/s]
 90% 214/238 [00:23<00:03,  7.45it/s]
 90% 215/238 [00:23<00:03,  7.34it/s]
 91% 217/238 [00:23<00:02,  8.73it/s]
 92% 218/238 [00:23<00:02,  8.23it/s]
 92% 219/238 [00:23<00:02,  7.97it/s]
 92% 220/238 [00:23<00:02,  7.96it/s]
 93% 221/238 [00:24<00:02,  7.78it/s]
 94% 223/238 [00:24<00:01,  9.31it/s]
 94% 224/238 [00:24<00:01,  9.33it/s]
 95% 225/238 [00:24<00:01,  9.21it/s]
 95% 226/238 [00:24<00:01,  9.16it/s]
 95% 227/238 [00:24<00:01,  9.03it/s]
 96% 229/238 [00:24<00:00,  9.93it/s]
 97% 230/238 [00:24<00:00,  9.26it/s]
 97% 232/238 [00:25<00:00,  9.08it/s]
 98% 233/238 [00:25<00:00,  9.07it/s]
 99% 235/238 [00:25<00:00,  9.33it/s]
 99% 236/238 [00:25<00:00,  8.93it/s]

{'eval_loss': 1.233980417251587, 'eval_accuracy': 0.47868421052631577, 'eval_macro_f1': 0.3592338054939117, 'eval_runtime': 25.9025, 'eval_samples_per_second': 293.409, 'eval_steps_per_second': 9.188, 'epoch': 1.0}
 33% 32/96 [00:30<00:08,  7.62it/s]
100% 238/238 [00:25<00:00, 10.45it/s]
{'loss': 0.7749, 'grad_norm': 2.3589351177215576, 'learning_rate': 9.583333333333335e-06, 'epoch': 1.56}
 67% 64/96 [00:34<00:04,  7.22it/s]
  0% 0/238 [00:00<?, ?it/s]
  1% 2/238 [00:00<00:13, 17.89it/s]
  2% 4/238 [00:00<00:25,  9.00it/s]
  3% 6/238 [00:00<00:25,  8.96it/s]
  3% 8/238 [00:00<00:27,  8.36it/s]
  4% 9/238 [00:01<00:28,  7.98it/s]
  4% 10/238 [00:01<00:29,  7.76it/s]
  5% 11/238 [00:01<00:27,  8.15it/s]
  5% 12/238 [00:01<00:27,  8.18it/s]
  6% 14/238 [00:01<00:26,  8.35it/s]
  6% 15/238 [00:01<00:27,  8.13it/s]
  7% 16/238 [00:01<00:26,  8.29it/s]
  7% 17/238 [00:01<00:25,  8.58it/s]
  8% 18/238 [00:02<00:27,  8.10it/s]
  8% 19/238 [00:02<00:26,  8.28it/s]
  8% 20/238 [00:02<00:27,  7.84it/s]
  9% 21/238 [00:02<00:28,  7.58it/s]
 10% 23/238 [00:02<00:25,  8.48it/s]
 10% 24/238 [00:02<00:26,  8.06it/s]
 11% 25/238 [00:03<00:27,  7.80it/s]
 11% 26/238 [00:03<00:25,  8.21it/s]
 11% 27/238 [00:03<00:24,  8.45it/s]
 12% 28/238 [00:03<00:25,  8.38it/s]
 12% 29/238 [00:03<00:25,  8.06it/s]
 13% 30/238 [00:03<00:24,  8.34it/s]
 13% 31/238 [00:03<00:25,  8.03it/s]
 13% 32/238 [00:03<00:26,  7.92it/s]
 14% 33/238 [00:03<00:25,  8.08it/s]
 14% 34/238 [00:04<00:25,  7.89it/s]
 15% 35/238 [00:04<00:26,  7.79it/s]
 15% 36/238 [00:04<00:26,  7.75it/s]
 16% 37/238 [00:04<00:24,  8.27it/s]
 16% 39/238 [00:04<00:23,  8.36it/s]
 17% 41/238 [00:04<00:22,  8.81it/s]
 18% 43/238 [00:05<00:21,  9.04it/s]
 18% 44/238 [00:05<00:21,  9.02it/s]
 19% 45/238 [00:05<00:22,  8.55it/s]
 20% 47/238 [00:05<00:21,  8.88it/s]
 21% 49/238 [00:05<00:19,  9.58it/s]
 21% 50/238 [00:05<00:20,  9.27it/s]
 21% 51/238 [00:06<00:22,  8.37it/s]
 22% 53/238 [00:06<00:21,  8.57it/s]
 23% 55/238 [00:06<00:21,  8.42it/s]
 24% 56/238 [00:06<00:21,  8.62it/s]
 24% 58/238 [00:06<00:21,  8.56it/s]
 25% 59/238 [00:06<00:20,  8.62it/s]
 25% 60/238 [00:07<00:20,  8.64it/s]
 26% 61/238 [00:07<00:21,  8.09it/s]
 26% 62/238 [00:07<00:22,  7.79it/s]
 26% 63/238 [00:07<00:23,  7.55it/s]
 27% 65/238 [00:07<00:20,  8.35it/s]
 28% 66/238 [00:07<00:21,  8.03it/s]
 29% 68/238 [00:08<00:20,  8.44it/s]
 29% 69/238 [00:08<00:21,  8.02it/s]
 29% 70/238 [00:08<00:20,  8.34it/s]
 30% 71/238 [00:08<00:20,  8.06it/s]
 30% 72/238 [00:08<00:21,  7.82it/s]
 31% 73/238 [00:08<00:21,  7.55it/s]
 31% 74/238 [00:08<00:22,  7.26it/s]
 32% 76/238 [00:09<00:20,  7.79it/s]
 32% 77/238 [00:09<00:21,  7.65it/s]
 33% 78/238 [00:09<00:19,  8.04it/s]
 33% 79/238 [00:09<00:19,  8.03it/s]
 34% 80/238 [00:09<00:20,  7.83it/s]
 34% 81/238 [00:09<00:20,  7.53it/s]
 35% 83/238 [00:09<00:17,  8.77it/s]
 35% 84/238 [00:10<00:18,  8.38it/s]
 36% 85/238 [00:10<00:19,  7.93it/s]
 36% 86/238 [00:10<00:18,  8.25it/s]
 37% 87/238 [00:10<00:19,  7.82it/s]
 37% 89/238 [00:10<00:18,  8.07it/s]
 38% 90/238 [00:10<00:19,  7.79it/s]
 39% 92/238 [00:11<00:18,  7.90it/s]
 39% 94/238 [00:11<00:16,  8.82it/s]
 40% 95/238 [00:11<00:16,  8.52it/s]
 41% 97/238 [00:11<00:16,  8.59it/s]
 41% 98/238 [00:11<00:17,  8.20it/s]
 42% 99/238 [00:11<00:17,  7.91it/s]
 42% 101/238 [00:12<00:16,  8.30it/s]
 43% 103/238 [00:12<00:15,  8.57it/s]
 44% 104/238 [00:12<00:15,  8.41it/s]
 44% 105/238 [00:12<00:15,  8.39it/s]
 45% 106/238 [00:12<00:15,  8.29it/s]
 45% 107/238 [00:12<00:15,  8.48it/s]
 46% 109/238 [00:13<00:14,  8.98it/s]
 46% 110/238 [00:13<00:14,  9.11it/s]
 47% 111/238 [00:13<00:14,  8.68it/s]
 47% 112/238 [00:13<00:15,  8.18it/s]
 47% 113/238 [00:13<00:15,  8.12it/s]
 48% 114/238 [00:13<00:14,  8.49it/s]
 48% 115/238 [00:13<00:15,  7.96it/s]
 49% 117/238 [00:14<00:13,  8.66it/s]
 50% 118/238 [00:14<00:14,  8.01it/s]
 50% 120/238 [00:14<00:14,  8.33it/s]
 51% 121/238 [00:14<00:14,  7.94it/s]
 52% 123/238 [00:14<00:13,  8.47it/s]
 52% 124/238 [00:14<00:13,  8.68it/s]
 53% 125/238 [00:15<00:13,  8.27it/s]
 53% 126/238 [00:15<00:14,  7.80it/s]
 54% 128/238 [00:15<00:13,  8.31it/s]
 54% 129/238 [00:15<00:13,  7.96it/s]
 55% 130/238 [00:15<00:13,  7.92it/s]
 55% 132/238 [00:15<00:11,  9.26it/s]
 56% 133/238 [00:15<00:11,  9.14it/s]
 56% 134/238 [00:16<00:12,  8.67it/s]
 57% 135/238 [00:16<00:12,  8.37it/s]
 57% 136/238 [00:16<00:12,  8.04it/s]
 58% 137/238 [00:16<00:12,  8.32it/s]
 58% 138/238 [00:16<00:11,  8.42it/s]
 58% 139/238 [00:16<00:11,  8.74it/s]
 59% 140/238 [00:16<00:11,  8.71it/s]
 59% 141/238 [00:16<00:11,  8.15it/s]
 60% 143/238 [00:17<00:11,  8.62it/s]
 61% 144/238 [00:17<00:10,  8.92it/s]
 61% 145/238 [00:17<00:10,  8.88it/s]
 61% 146/238 [00:17<00:10,  8.77it/s]
 62% 147/238 [00:17<00:10,  8.38it/s]
 62% 148/238 [00:17<00:10,  8.24it/s]
 63% 149/238 [00:17<00:10,  8.58it/s]
 63% 150/238 [00:18<00:10,  8.10it/s]
 63% 151/238 [00:18<00:10,  8.28it/s]
 64% 152/238 [00:18<00:10,  8.03it/s]
 64% 153/238 [00:18<00:10,  8.40it/s]
 65% 154/238 [00:18<00:09,  8.77it/s]
 66% 156/238 [00:18<00:08,  9.30it/s]
 66% 158/238 [00:18<00:07, 10.15it/s]
 67% 160/238 [00:19<00:07,  9.76it/s]
 68% 161/238 [00:19<00:08,  9.11it/s]
 68% 162/238 [00:19<00:08,  8.66it/s]
 68% 163/238 [00:19<00:09,  8.18it/s]
 69% 164/238 [00:19<00:09,  7.78it/s]
 70% 166/238 [00:19<00:08,  8.09it/s]
 70% 167/238 [00:19<00:09,  7.87it/s]
 71% 168/238 [00:20<00:09,  7.73it/s]
 71% 169/238 [00:20<00:09,  7.66it/s]
 71% 170/238 [00:20<00:08,  8.08it/s]
 72% 171/238 [00:20<00:08,  7.59it/s]
 73% 173/238 [00:20<00:07,  8.90it/s]
 73% 174/238 [00:20<00:07,  8.63it/s]
 74% 176/238 [00:21<00:07,  8.66it/s]
 74% 177/238 [00:21<00:07,  8.43it/s]
 75% 179/238 [00:21<00:06,  8.84it/s]
 76% 180/238 [00:21<00:06,  8.44it/s]
 76% 181/238 [00:21<00:06,  8.16it/s]
 76% 182/238 [00:21<00:06,  8.40it/s]
 77% 184/238 [00:21<00:05,  9.23it/s]
 78% 185/238 [00:22<00:06,  8.56it/s]
 78% 186/238 [00:22<00:06,  8.21it/s]
 79% 187/238 [00:22<00:06,  7.86it/s]
 79% 188/238 [00:22<00:06,  7.66it/s]
 79% 189/238 [00:22<00:06,  7.57it/s]
 80% 190/238 [00:22<00:06,  7.68it/s]
 81% 192/238 [00:22<00:05,  9.04it/s]
 81% 193/238 [00:23<00:04,  9.18it/s]
 82% 194/238 [00:23<00:04,  9.14it/s]
 82% 196/238 [00:23<00:04, 10.16it/s]
 83% 197/238 [00:23<00:04,  9.30it/s]
 83% 198/238 [00:23<00:04,  8.70it/s]
 84% 200/238 [00:23<00:04,  9.33it/s]
 84% 201/238 [00:23<00:04,  8.99it/s]
 85% 203/238 [00:24<00:03,  9.68it/s]
 86% 204/238 [00:24<00:03,  9.61it/s]
 87% 206/238 [00:24<00:03,  9.33it/s]
 87% 207/238 [00:24<00:03,  8.80it/s]
 87% 208/238 [00:24<00:03,  8.31it/s]
 88% 209/238 [00:24<00:03,  8.66it/s]
 88% 210/238 [00:24<00:03,  8.25it/s]
 89% 211/238 [00:25<00:03,  8.18it/s]
 89% 212/238 [00:25<00:03,  7.81it/s]
 89% 213/238 [00:25<00:03,  7.66it/s]
 90% 214/238 [00:25<00:03,  7.52it/s]
 90% 215/238 [00:25<00:03,  7.49it/s]
 91% 217/238 [00:25<00:02,  8.94it/s]
 92% 218/238 [00:25<00:02,  8.42it/s]
 92% 219/238 [00:26<00:02,  8.16it/s]
 92% 220/238 [00:26<00:02,  8.07it/s]
 93% 221/238 [00:26<00:02,  7.90it/s]
 94% 223/238 [00:26<00:01,  9.40it/s]
 94% 224/238 [00:26<00:01,  9.39it/s]
 95% 225/238 [00:26<00:01,  9.31it/s]
 95% 226/238 [00:26<00:01,  9.31it/s]
 95% 227/238 [00:26<00:01,  9.21it/s]
 96% 229/238 [00:27<00:00, 10.16it/s]
 97% 230/238 [00:27<00:00,  9.52it/s]
 97% 232/238 [00:27<00:00,  9.41it/s]
 98% 233/238 [00:27<00:00,  9.31it/s]
 99% 235/238 [00:27<00:00,  9.60it/s]
 99% 236/238 [00:27<00:00,  9.17it/s]

{'eval_loss': 0.938984751701355, 'eval_accuracy': 0.6578947368421053, 'eval_macro_f1': 0.5717480099747558, 'eval_runtime': 28.1829, 'eval_samples_per_second': 269.667, 'eval_steps_per_second': 8.445, 'epoch': 2.0}
 67% 64/96 [01:03<00:04,  7.22it/s]
100% 238/238 [00:28<00:00, 10.83it/s]
100% 96/96 [01:07<00:00,  7.88it/s]
  0% 0/238 [00:00<?, ?it/s]
  1% 2/238 [00:00<00:12, 18.36it/s]
  2% 4/238 [00:00<00:24,  9.71it/s]
  3% 6/238 [00:00<00:24,  9.53it/s]
  3% 8/238 [00:00<00:25,  8.97it/s]
  4% 9/238 [00:00<00:26,  8.58it/s]
  4% 10/238 [00:01<00:27,  8.32it/s]
  5% 12/238 [00:01<00:25,  8.85it/s]
  6% 14/238 [00:01<00:24,  8.96it/s]
  6% 15/238 [00:01<00:25,  8.81it/s]
  7% 16/238 [00:01<00:24,  8.96it/s]
  8% 18/238 [00:01<00:24,  8.90it/s]
  8% 19/238 [00:02<00:24,  9.01it/s]
  8% 20/238 [00:02<00:25,  8.60it/s]
  9% 21/238 [00:02<00:26,  8.29it/s]
 10% 23/238 [00:02<00:23,  9.15it/s]
 10% 24/238 [00:02<00:24,  8.78it/s]
 11% 25/238 [00:02<00:25,  8.46it/s]
 11% 27/238 [00:02<00:23,  9.13it/s]
 12% 28/238 [00:03<00:22,  9.15it/s]
 12% 29/238 [00:03<00:23,  8.94it/s]
 13% 31/238 [00:03<00:22,  9.02it/s]
 13% 32/238 [00:03<00:23,  8.87it/s]
 14% 33/238 [00:03<00:22,  9.01it/s]
 14% 34/238 [00:03<00:23,  8.85it/s]
 15% 35/238 [00:03<00:23,  8.73it/s]
 15% 36/238 [00:04<00:23,  8.61it/s]
 16% 38/238 [00:04<00:20,  9.59it/s]
 16% 39/238 [00:04<00:22,  8.95it/s]
 17% 41/238 [00:04<00:20,  9.63it/s]
 18% 43/238 [00:04<00:19,  9.85it/s]
 19% 45/238 [00:04<00:20,  9.55it/s]
 20% 47/238 [00:05<00:19,  9.94it/s]
 21% 49/238 [00:05<00:17, 10.68it/s]
 21% 51/238 [00:05<00:19,  9.76it/s]
 22% 53/238 [00:05<00:18,  9.87it/s]
 23% 55/238 [00:05<00:18,  9.71it/s]
 24% 57/238 [00:06<00:17, 10.22it/s]
 25% 59/238 [00:06<00:18,  9.73it/s]
 25% 60/238 [00:06<00:18,  9.76it/s]
 26% 61/238 [00:06<00:19,  9.29it/s]
 26% 62/238 [00:06<00:19,  8.85it/s]
 26% 63/238 [00:06<00:20,  8.59it/s]
 27% 65/238 [00:07<00:18,  9.40it/s]
 28% 66/238 [00:07<00:19,  9.02it/s]
 29% 68/238 [00:07<00:17,  9.57it/s]
 29% 69/238 [00:07<00:18,  9.14it/s]
 30% 71/238 [00:07<00:18,  9.23it/s]
 30% 72/238 [00:07<00:18,  9.01it/s]
 31% 73/238 [00:07<00:19,  8.58it/s]
 31% 74/238 [00:08<00:19,  8.24it/s]
 32% 76/238 [00:08<00:18,  8.76it/s]
 32% 77/238 [00:08<00:18,  8.54it/s]
 33% 79/238 [00:08<00:17,  8.96it/s]
 34% 80/238 [00:08<00:17,  8.81it/s]
 34% 81/238 [00:08<00:18,  8.54it/s]
 35% 83/238 [00:09<00:15,  9.81it/s]
 35% 84/238 [00:09<00:16,  9.43it/s]
 36% 85/238 [00:09<00:16,  9.01it/s]
 37% 87/238 [00:09<00:16,  8.99it/s]
 37% 89/238 [00:09<00:16,  9.11it/s]
 38% 90/238 [00:09<00:16,  8.80it/s]
 39% 92/238 [00:10<00:16,  8.87it/s]
 39% 94/238 [00:10<00:14,  9.77it/s]
 40% 95/238 [00:10<00:15,  9.45it/s]
 41% 97/238 [00:10<00:14,  9.46it/s]
 41% 98/238 [00:10<00:15,  9.08it/s]
 42% 99/238 [00:10<00:15,  8.73it/s]
 42% 101/238 [00:10<00:14,  9.15it/s]
 43% 103/238 [00:11<00:14,  9.46it/s]
 44% 104/238 [00:11<00:14,  9.21it/s]
 44% 105/238 [00:11<00:14,  9.21it/s]
 45% 106/238 [00:11<00:14,  9.21it/s]
 45% 108/238 [00:11<00:12, 10.07it/s]
 46% 109/238 [00:11<00:13,  9.87it/s]
 47% 111/238 [00:12<00:13,  9.69it/s]
 47% 112/238 [00:12<00:13,  9.14it/s]
 47% 113/238 [00:12<00:13,  9.02it/s]
 48% 115/238 [00:12<00:13,  8.88it/s]
 49% 117/238 [00:12<00:12,  9.51it/s]
 50% 118/238 [00:12<00:13,  8.92it/s]
 50% 120/238 [00:13<00:12,  9.10it/s]
 51% 121/238 [00:13<00:13,  8.75it/s]
 52% 123/238 [00:13<00:12,  9.41it/s]
 52% 124/238 [00:13<00:11,  9.51it/s]
 53% 125/238 [00:13<00:12,  9.03it/s]
 53% 126/238 [00:13<00:13,  8.55it/s]
 54% 128/238 [00:13<00:12,  9.04it/s]
 54% 129/238 [00:14<00:12,  8.67it/s]
 55% 130/238 [00:14<00:12,  8.68it/s]
 55% 132/238 [00:14<00:10, 10.17it/s]
 56% 134/238 [00:14<00:10,  9.61it/s]
 57% 135/238 [00:14<00:11,  9.27it/s]
 57% 136/238 [00:14<00:11,  8.82it/s]
 58% 138/238 [00:15<00:10,  9.18it/s]
 59% 140/238 [00:15<00:10,  9.48it/s]
 59% 141/238 [00:15<00:10,  9.07it/s]
 60% 143/238 [00:15<00:09,  9.50it/s]
 61% 145/238 [00:15<00:09,  9.61it/s]
 61% 146/238 [00:15<00:09,  9.57it/s]
 62% 147/238 [00:15<00:09,  9.27it/s]
 62% 148/238 [00:16<00:09,  9.09it/s]
 63% 150/238 [00:16<00:09,  9.02it/s]
 63% 151/238 [00:16<00:09,  9.20it/s]
 64% 152/238 [00:16<00:09,  8.99it/s]
 65% 154/238 [00:16<00:08,  9.53it/s]
 66% 156/238 [00:16<00:08,  9.98it/s]
 66% 158/238 [00:17<00:07, 10.63it/s]
 67% 160/238 [00:17<00:07, 10.42it/s]
 68% 162/238 [00:17<00:08,  9.47it/s]
 68% 163/238 [00:17<00:08,  9.03it/s]
 69% 164/238 [00:17<00:08,  8.68it/s]
 70% 166/238 [00:17<00:08,  8.88it/s]
 70% 167/238 [00:18<00:08,  8.67it/s]
 71% 168/238 [00:18<00:08,  8.52it/s]
 71% 169/238 [00:18<00:08,  8.34it/s]
 71% 170/238 [00:18<00:07,  8.72it/s]
 72% 171/238 [00:18<00:08,  8.23it/s]
 73% 173/238 [00:18<00:06,  9.60it/s]
 73% 174/238 [00:18<00:06,  9.19it/s]
 74% 176/238 [00:19<00:06,  9.30it/s]
 74% 177/238 [00:19<00:06,  9.12it/s]
 75% 179/238 [00:19<00:06,  9.51it/s]
 76% 180/238 [00:19<00:06,  9.07it/s]
 76% 181/238 [00:19<00:06,  8.74it/s]
 76% 182/238 [00:19<00:06,  8.88it/s]
 77% 184/238 [00:19<00:05,  9.77it/s]
 78% 185/238 [00:20<00:05,  9.09it/s]
 78% 186/238 [00:20<00:05,  8.78it/s]
 79% 187/238 [00:20<00:06,  8.36it/s]
 79% 188/238 [00:20<00:06,  8.22it/s]
 79% 189/238 [00:20<00:06,  8.06it/s]
 80% 190/238 [00:20<00:05,  8.13it/s]
 81% 192/238 [00:20<00:04,  9.59it/s]
 82% 194/238 [00:21<00:04,  9.64it/s]
 82% 196/238 [00:21<00:03, 10.62it/s]
 83% 198/238 [00:21<00:04,  9.47it/s]

In [8]:
!find outputs -maxdepth 3 -type f -printf "%p\n"

outputs/fewshot_curve.png
outputs/summary_report.md
outputs/full_finetune_report.json
outputs/full_run/final_model/tokenizer_config.json
outputs/full_run/final_model/model.safetensors
outputs/full_run/final_model/vocab.txt
outputs/full_run/final_model/training_args.bin
outputs/full_run/final_model/tokenizer.json
outputs/full_run/final_model/special_tokens_map.json
outputs/full_run/final_model/config.json
outputs/error_confusion_pairs.csv
outputs/baseline_report.json
outputs/error_analysis.csv
outputs/bayes_run/final_model/tokenizer_config.json
outputs/bayes_run/final_model/model.safetensors
outputs/bayes_run/final_model/vocab.txt
outputs/bayes_run/final_model/training_args.bin
outputs/bayes_run/final_model/tokenizer.json
outputs/bayes_run/final_model/special_tokens_map.json
outputs/bayes_run/final_model/config.json
outputs/lora_run/final_model/tokenizer_config.json
outputs/lora_run/final_model/README.md
outputs/lora_run/final_model/vocab.txt
outputs/lora_run/final_model/training_args.bin
outputs/lora_run/final_model/adapter_config.json
outputs/lora_run/final_model/tokenizer.json
outputs/lora_run/final_model/special_tokens_map.json
outputs/lora_run/final_model/adapter_model.safetensors
outputs/bayes_correction_report.json
outputs/lora_finetune_report.json
outputs/fewshot_curve.json

In [9]:
!zip -r /content/AG_News_outputs.zip outputs/

  adding: outputs/ (stored 0%)
  adding: outputs/fewshot_frac_0.05/ (stored 0%)
  adding: outputs/fewshot_curve.png (deflated 11%)
  adding: outputs/summary_report.md (deflated 70%)
  adding: outputs/fewshot_frac_0.02/ (stored 0%)
  adding: outputs/full_finetune_report.json (deflated 68%)
  adding: outputs/full_run/ (stored 0%)
  adding: outputs/full_run/final_model/ (stored 0%)
  adding: outputs/full_run/final_model/tokenizer_config.json (deflated 76%)
  adding: outputs/full_run/final_model/model.safetensors (deflated 8%)
  adding: outputs/full_run/final_model/vocab.txt (deflated 53%)
  adding: outputs/full_run/final_model/training_args.bin (deflated 51%)
  adding: outputs/full_run/final_model/tokenizer.json (deflated 71%)
  adding: outputs/full_run/final_model/special_tokens_map.json (deflated 42%)
  adding: outputs/full_run/final_model/config.json (deflated 50%)
  adding: outputs/error_confusion_pairs.csv (deflated 54%)
  adding: outputs/fewshot_frac_0.5/ (stored 0%)
  adding: outputs/fewshot_frac_0.1/ (stored 0%)
  adding: outputs/baseline_report.json (deflated 70%)
  adding: outputs/fewshot_frac_0.25/ (stored 0%)
  adding: outputs/error_analysis.csv (deflated 50%)
  adding: outputs/bayes_run/ (stored 0%)
  adding: outputs/bayes_run/final_model/ (stored 0%)
  adding: outputs/bayes_run/final_model/tokenizer_config.json (deflated 76%)
  adding: outputs/bayes_run/final_model/model.safetensors (deflated 8%)
  adding: outputs/bayes_run/final_model/vocab.txt (deflated 53%)
  adding: outputs/bayes_run/final_model/training_args.bin (deflated 51%)
  adding: outputs/bayes_run/final_model/tokenizer.json (deflated 71%)
  adding: outputs/bayes_run/final_model/special_tokens_map.json (deflated 42%)
  adding: outputs/bayes_run/final_model/config.json (deflated 50%)
  adding: outputs/lora_run/ (stored 0%)
  adding: outputs/lora_run/final_model/ (stored 0%)
  adding: outputs/lora_run/final_model/tokenizer_config.json (deflated 76%)
  adding: outputs/lora_run/final_model/README.md (deflated 66%)
  adding: outputs/lora_run/final_model/vocab.txt (deflated 53%)
  adding: outputs/lora_run/final_model/training_args.bin (deflated 51%)
  adding: outputs/lora_run/final_model/adapter_config.json (deflated 54%)
  adding: outputs/lora_run/final_model/tokenizer.json (deflated 71%)
  adding: outputs/lora_run/final_model/special_tokens_map.json (deflated 42%)
  adding: outputs/lora_run/final_model/adapter_model.safetensors (deflated 7%)
  adding: outputs/fewshot_frac_0.01/ (stored 0%)
  adding: outputs/bayes_correction_report.json (deflated 77%)
  adding: outputs/lora_finetune_report.json (deflated 67%)
  adding: outputs/fewshot_frac_1.0/ (stored 0%)
  adding: outputs/fewshot_curve.json (deflated 85%)

In [10]:
from google.colab import files
files.download("/content/AG_News_outputs.zip")